'use strict';
// BigInt rational validation of the explicit perturbation and uniform sonar bounds.
const gcd=(a,b)=>{a=a<0n?-a:a;b=b<0n?-b:b;while(b){const t=a%b;a=b;b=t;}return a;};
class Q{constructor(n,d=1n){n=BigInt(n);d=BigInt(d);if(!d)throw Error('zero denominator');if(d<0n){n=-n;d=-d;}const g=gcd(n,d);this.n=n/g;this.d=d/g;}add(b){return new Q(this.n*b.d+b.n*this.d,this.d*b.d);}sub(b){return this.add(new Q(-b.n,b.d));}mul(b){return new Q(this.n*b.n,this.d*b.d);}div(b){return new Q(this.n*b.d,this.d*b.n);}pow(n){return new Q(this.n**BigInt(n),this.d**BigInt(n));}cmp(b){const v=this.n*b.d-b.n*this.d;return v<0n?-1:v>0n?1:0;}}
const q=(n,d=1)=>new Q(n,d),one=q(1),zero=q(0);let checks=0;
const ck=(v,s)=>{checks++;if(!v)throw Error(s);};
const delta=q(1,16),theta=q(1,10000000),a0Lo=q(9,8),a0Hi=q(121,98);
const K=q(16).mul(one.add(q(2).div(delta.pow(2))).pow(2));
ck(K.cmp(q(4210704))===0,'uniform Fourier ratio K');
ck(theta.mul(K).cmp(one)<0,'Fourier positivity margin');
ck(q(32).mul(theta).cmp(q(1,2))<0,'central pointwise positivity');
ck(q(15,16).mul(q(31,32)).cmp(q(465,512))===0,'central cosine lower envelope');
const af=one.sub(q(32).mul(theta)),M=q(1,4).add(q(127,32).mul(theta));
const R=one.sub(q(129,8).mul(theta)).sub(q(508).mul(theta.pow(2)));
ck(af.mul(M).mul(q(4)).cmp(R)===0,'strict product identity');
ck(R.cmp(zero)>0&&R.cmp(one)<0,'strict improvement over pi²/32');
ck(a0Lo.mul(af).cmp(one)>0,'a>=1');
ck(a0Hi.mul(af).cmp(q(4,3))<0,'a<=4/3');
ck(M.cmp(q(1,4))>=0&&M.cmp(q(1,3))<0,'moment bracket');
ck(q(1,4).mul(R).cmp(q(3,5).pow(3))>0,'v lower bracket using pi>3');
ck(q(121,441).mul(R).cmp(q(2,3).pow(3))<0,'v upper bracket using pi<22/7');
ck(a0Hi.mul(q(2).add(q(128).mul(theta))).cmp(q(3))<0,'variation f bound');
ck(q(2).add(theta.mul(q(6).add(q(132).mul(a0Hi)))).cmp(q(3))<0,'variation |x|f bound');
const x=q(160),tLo=q(9,5),tHi=q(8,3),vHi=q(2,3),vLo=q(3,5),eps=one.div(x.pow(4));
ck(q(33,16).mul(tHi).cmp(q(11,2))===0,'support radius times scale');
ck(q(11,2).cmp(x)<0,'support fits when m>=n');
const dHi=q(3).add(q(8,9).mul(q(4,3))).div(tLo),eHi=q(4,3).mul(q(4,3)).div(tLo);
ck(dHi.cmp(q(565,243))===0&&dHi.cmp(q(3))<0,'d bound');
ck(eHi.cmp(q(80,81))===0&&eHi.cmp(one)<0,'e bound');
ck(vHi.div(x).add(q(3).add(eps).div(x.pow(2))).cmp(q(1,2))<0,'positive denominator');
ck(q(8).div(q(9).mul(vLo)).add(q(2).div(tLo)).cmp(q(70,27))===0,'linear numerator coefficient');
ck(q(16).div(q(9).mul(vLo).mul(tLo).mul(x)).cmp(one)<0,'first inverse-x term');
ck(q(16).div(q(9).mul(tLo).mul(x.pow(2))).cmp(one)<0,'second inverse-x term');
ck(eps.mul(x.pow(2).add(q(4,3))).mul(one.add(q(2).div(tLo.mul(x.pow(2))))).cmp(one)<0,'numerator tail');
ck(q(41,9).add(q(3)).cmp(q(8))<0,'remaining numerator below8');
ck(q(8).sub(q(4,3)).sub(q(3)).sub(q(70,27)).cmp(q(29,27))===0,'final linear margin');
ck(q(8).mul(q(3)).div(x).cmp(one)<0,'8d/x bound');
ck(eps.mul(x.add(q(3).mul(vHi)).add(q(8).div(x))).cmp(one)<0,'denominator tail');
ck(q(16,3).add(q(6)).add(q(1)).add(q(8)).add(q(1)).cmp(q(22))<0,'final constants below22');
ck(q(29,27).mul(x).sub(q(22)).cmp(zero)>0,'positive final margin');
ck(200n*160n**4n<2n**40n,'uniform exponential bound');
console.log(JSON.stringify({result:'PASS',exactRationalChecks:checks,theta:'1/10000000',delta:'1/16',scope:'Analytic admissibility is proved in KERNEL_PERTURBATION.md; this script checks every rational envelope in its uniform bounds.'},null,2));
