"""
meataxe.py -- self-contained modular MeatAxe over prime fields F_p.

Pure Python integer arithmetic mod p.  EXACT.  No floating point anywhere.
No numpy (the sympy venv has none).  sympy is used ONLY to factor univariate
polynomials over F_p.

Everything here is generic: a "module" is a list of d x d matrices over F_p,
one per group generator.

Round 2 of line zc1a7.  owner-zc1a7.
"""
import random
from sympy import Poly, symbols

_X = symbols('x')


# ---------------------------------------------------------------- linear algebra

def mat_mul(A, B, p):
    Bt = list(zip(*B))
    return [[sum(a * b for a, b in zip(row, col)) % p for col in Bt] for row in A]


def mat_vec(A, v, p):
    return [sum(a * b for a, b in zip(row, v)) % p for row in A]


def mat_id(n):
    return [[1 if i == j else 0 for j in range(n)] for i in range(n)]


def mat_transpose(A):
    return [list(r) for r in zip(*A)]


def mat_sub(A, B, p):
    return [[(a - b) % p for a, b in zip(ra, rb)] for ra, rb in zip(A, B)]


def rref(rows, p):
    """Row-reduce.  Returns (echelon rows with leading 1s, pivot column list)."""
    M = [list(r) for r in rows]
    ncols = len(M[0]) if M else 0
    pivots = []
    r = 0
    for c in range(ncols):
        piv = None
        for i in range(r, len(M)):
            if M[i][c] % p:
                piv = i
                break
        if piv is None:
            continue
        M[r], M[piv] = M[piv], M[r]
        inv = pow(M[r][c], p - 2, p)
        M[r] = [(x * inv) % p for x in M[r]]
        for i in range(len(M)):
            if i != r and M[i][c] % p:
                f = M[i][c]
                M[i] = [(a - f * b) % p for a, b in zip(M[i], M[r])]
        pivots.append(c)
        r += 1
        if r == len(M):
            break
    return [row for row in M[:r]], pivots


def rank(rows, p):
    if not rows:
        return 0
    return len(rref(rows, p)[0])


def nullspace(A, p):
    """Basis of {v : A v = 0}, A a list of rows.  Returns list of vectors."""
    n = len(A[0])
    E, piv = rref(A, p)
    free = [c for c in range(n) if c not in piv]
    basis = []
    for f in free:
        v = [0] * n
        v[f] = 1
        for i, c in enumerate(piv):
            v[c] = (-E[i][f]) % p
        basis.append(v)
    return basis


def echelon_insert(basis, pivots, v, p):
    """Reduce v against an echelonized basis; if independent, append. Return True if added."""
    w = list(v)
    for b, c in zip(basis, pivots):
        if w[c] % p:
            f = w[c]
            w = [(x - f * y) % p for x, y in zip(w, b)]
    for c, x in enumerate(w):
        if x % p:
            inv = pow(x, p - 2, p)
            w = [(y * inv) % p for y in w]
            basis.append(w)
            pivots.append(c)
            return True
    return False


# ---------------------------------------------------------------- spinning

def spin(vectors, gens, p):
    """Submodule generated by `vectors`.  Returns echelonized basis (list of rows)."""
    basis, pivots = [], []
    queue = []
    for v in vectors:
        if echelon_insert(basis, pivots, v, p):
            queue.append(list(v))
    # spin the *original* vectors, not the reduced ones: keep a separate work list
    work = [list(v) for v in vectors]
    idx = 0
    while idx < len(work):
        w = work[idx]
        idx += 1
        for g in gens:
            gw = mat_vec(g, w, p)
            if echelon_insert(basis, pivots, gw, p):
                work.append(gw)
    return basis


def spin_standard(v, gens, p):
    """Spin v recording words.  Returns (vectors, words) where words[j] = (parent, gen)
    with words[0] = None, vectors[j] = gens[gen] * vectors[parent].
    `vectors` is a basis of the submodule generated by v (NOT echelonized)."""
    vecs = [list(v)]
    words = [None]
    basis, pivots = [], []
    echelon_insert(basis, pivots, v, p)
    idx = 0
    while idx < len(vecs):
        w = vecs[idx]
        for gi, g in enumerate(gens):
            gw = mat_vec(g, w, p)
            if echelon_insert(basis, pivots, gw, p):
                vecs.append(gw)
                words.append((idx, gi))
        idx += 1
    return vecs, words


# ---------------------------------------------------------------- polynomials over F_p

def poly_trim(c, p):
    c = [x % p for x in c]
    while len(c) > 1 and c[-1] == 0:
        c.pop()
    return c


def poly_eval_mat(coeffs, A, p):
    """coeffs[i] = coefficient of x^i.  Horner."""
    n = len(A)
    R = [[0] * n for _ in range(n)]
    for c in reversed(coeffs):
        R = mat_mul(R, A, p)
        for i in range(n):
            R[i][i] = (R[i][i] + c) % p
    return R


def krylov_minpoly(A, v, p):
    """Minimal polynomial of v under A.  Returns coeff list (monic, low->high)."""
    n = len(v)
    rows = []          # augmented rows: [ vector | coeffs of A^0..A^k ]
    pivots = []
    cur = list(v)
    k = 0
    while True:
        for i in range(len(rows)):
            while len(rows[i]) < n + k + 1:
                rows[i].append(0)
        aug = list(cur) + [0] * (k + 1)
        aug[n + k] = 1
        w = aug
        for r, c in zip(rows, pivots):
            if w[c] % p:
                f = w[c]
                w = [(x - f * y) % p for x, y in zip(w, r)]
        lead = None
        for c in range(n):
            if w[c] % p:
                lead = c
                break
        if lead is None:
            # dependency found: tail gives the minimal polynomial of v
            return poly_trim(_monic(w[n:], p), p)
        inv = pow(w[lead], p - 2, p)
        w = [(x * inv) % p for x in w]
        rows.append(w)
        pivots.append(lead)
        cur = mat_vec(A, cur, p)
        k += 1


def _monic(coeffs, p):
    c = [x % p for x in coeffs]
    while len(c) > 1 and c[-1] == 0:
        c.pop()
    inv = pow(c[-1], p - 2, p)
    return [(x * inv) % p for x in c]


def factor_modp(coeffs, p):
    """Factor a monic polynomial over F_p.  Returns list of (coeff list, multiplicity)."""
    poly = Poly(list(reversed(coeffs)), _X, modulus=p)
    out = []
    _, facs = poly.factor_list()
    for f, m in facs:
        cs = [int(c) % p for c in reversed(f.all_coeffs())]
        out.append((poly_trim(cs, p), m))
    return out


# ---------------------------------------------------------------- module surgery

def restrict(gens, basis, p):
    """Action of gens on the submodule with the given (echelonized) basis."""
    E, piv = rref(basis, p)
    d = len(E)
    new = []
    for g in gens:
        cols = []
        for b in E:
            gb = mat_vec(g, b, p)
            # solve gb = sum c_i E_i  using pivot columns
            c = []
            w = list(gb)
            for i in range(d):
                ci = w[piv[i]] % p
                c.append(ci)
                if ci:
                    w = [(x - ci * y) % p for x, y in zip(w, E[i])]
            assert all(x % p == 0 for x in w), "restrict: not a submodule"
            cols.append(c)
        # cols[j] = coordinates of g*E_j ; matrix acts on column vectors
        new.append([[cols[j][i] for j in range(d)] for i in range(d)])
    return new


def quotient(gens, basis, p):
    """Action of gens on V / W where W has the given basis."""
    E, piv = rref(basis, p)
    n = len(gens[0])
    free = [c for c in range(n) if c not in piv]
    d = len(free)

    def reduce_vec(w):
        w = list(w)
        for i, c in enumerate(piv):
            if w[c] % p:
                f = w[c]
                w = [(x - f * y) % p for x, y in zip(w, E[i])]
        return [w[c] % p for c in free]

    new = []
    for g in gens:
        cols = []
        for c in free:
            e = [0] * n
            e[c] = 1
            cols.append(reduce_vec(mat_vec(g, e, p)))
        new.append([[cols[j][i] for j in range(d)] for i in range(d)])
    return new


def tensor(gensA, gensB, p):
    da, db = len(gensA[0]), len(gensB[0])
    out = []
    for A, B in zip(gensA, gensB):
        M = [[0] * (da * db) for _ in range(da * db)]
        for i in range(da):
            for j in range(da):
                aij = A[i][j]
                if aij == 0:
                    continue
                for k in range(db):
                    for l in range(db):
                        if B[k][l]:
                            M[i * db + k][j * db + l] = (aij * B[k][l]) % p
        out.append(M)
    return out


# ---------------------------------------------------------------- Norton's test

def _proj_points(vs, p):
    """All projective points of the span of vs (vs a basis).  Small e only."""
    e = len(vs)
    n = len(vs[0])
    pts = []
    # vectors with leading nonzero coordinate = 1 in the coefficient space
    def rec(i, coeffs):
        if i == e:
            if any(c % p for c in coeffs):
                v = [0] * n
                for c, b in zip(coeffs, vs):
                    if c:
                        v = [(x + c * y) % p for x, y in zip(v, b)]
                pts.append(v)
            return
        # normalise: first nonzero coefficient is 1
        if all(c == 0 for c in coeffs[:i]):
            rng = [0, 1]
        else:
            rng = range(p)
        for c in rng:
            rec(i + 1, coeffs + [c])
    rec(0, [])
    return pts


def find_submodule(gens, p, tries=30, seed=12345, max_nullity=4):
    """Try to find a proper nonzero submodule.
    Returns ('reducible', basis) | ('irreducible', witness) | ('unknown', None)."""
    n = len(gens[0])
    if n == 1:
        return ('irreducible', 'dim 1')
    rnd = random.Random(seed)
    gensT = [mat_transpose(g) for g in gens]
    words = list(gens)
    for t in range(tries):
        # random algebra element: random word product plus random linear combination
        x = mat_id(n)
        for _ in range(rnd.randint(1, 6)):
            x = mat_mul(x, gens[rnd.randrange(len(gens))], p)
        y = mat_id(n)
        for _ in range(rnd.randint(1, 6)):
            y = mat_mul(y, gens[rnd.randrange(len(gens))], p)
        a, b = rnd.randrange(1, p), rnd.randrange(p)
        x = [[(a * u + b * v) % p for u, v in zip(rx, ry)] for rx, ry in zip(x, y)]

        v = [rnd.randrange(p) for _ in range(n)]
        if not any(v):
            continue
        mp = krylov_minpoly(x, v, p)
        if len(mp) <= 1:
            continue
        facs = factor_modp(mp, p)
        # order irreducible factors by nullity of f(x)
        cand = []
        for f, m in facs:
            if len(f) - 1 == 0:
                continue
            Nf = poly_eval_mat(f, x, p)
            ker = nullspace(Nf, p)
            if ker:
                cand.append((len(ker), f, Nf, ker))
        cand.sort(key=lambda z: z[0])
        for e, f, Nf, ker in cand:
            if e > max_nullity:
                continue
            # (a) spin every projective point of ker
            for w in _proj_points(ker, p):
                B = spin([w], gens, p)
                if 0 < len(B) < n:
                    return ('reducible', B)
            # (b) dual side
            NfT = mat_transpose(Nf)
            kerT = nullspace(NfT, p)
            for w in _proj_points(kerT, p):
                B = spin([w], gensT, p)
                if 0 < len(B) < n:
                    # B spans a proper submodule of the dual -> its annihilator
                    # is a proper submodule of the original module
                    ann = nullspace(B, p)
                    return ('reducible', ann)
            # both sides exhausted with full spins => Norton: irreducible
            return ('irreducible', ('norton', e, f))
    return ('unknown', None)


def chop(gens, p, seed=1):
    """Composition factors WITH multiplicity.  Returns list of gens-lists."""
    out = []
    stack = [(gens, seed)]
    while stack:
        m, sd = stack.pop()
        n = len(m[0])
        if n == 0:
            continue
        status, data = find_submodule(m, p, seed=sd)
        if status == 'irreducible':
            out.append(m)
        elif status == 'reducible':
            W = data
            stack.append((restrict(m, W, p), sd + 7))
            stack.append((quotient(m, W, p), sd + 13))
        else:
            raise RuntimeError("MeatAxe: undecided module of dimension %d" % n)
    return out


# ---------------------------------------------------------------- Hom / End

def hom_dim(gensS, gensT, p, seed=3):
    """dim Hom_{F_pG}(S, T) for S irreducible (spinning any nonzero vector of S
    must fill S).  Returns (dimension, one nonzero hom matrix or None)."""
    dS = len(gensS[0])
    dT = len(gensT[0])
    rnd = random.Random(seed)
    for _ in range(20):
        v = [rnd.randrange(p) for _ in range(dS)]
        if any(v):
            vecs, words = spin_standard(v, gensS, p)
            if len(vecs) == dS:
                break
    else:
        raise RuntimeError("hom_dim: could not spin a basis of S")

    B = [[vecs[j][i] for j in range(dS)] for i in range(dS)]     # columns = vecs
    Binv = mat_inverse(B, p)

    Xs = []
    for l in range(dT):
        w0 = [0] * dT
        w0[l] = 1
        cs = [w0]
        for j in range(1, dS):
            par, gi = words[j]
            cs.append(mat_vec(gensT[gi], cs[par], p))
        C = [[cs[j][i] for j in range(dS)] for i in range(dT)]   # dT x dS
        Xs.append(mat_mul(C, Binv, p))
    # D[l][gi] = Xs[l]*gS - gT*Xs[l]
    D = [[mat_sub(mat_mul(Xs[l], gensS[gi], p), mat_mul(gensT[gi], Xs[l], p), p)
          for gi in range(len(gensS))] for l in range(dT)]
    eqs = []
    for gi in range(len(gensS)):
        for i in range(dT):
            for j in range(dS):
                eqs.append([D[l][gi][i][j] for l in range(dT)])
    ns = nullspace(eqs, p)
    if not ns:
        return 0, None
    coef = ns[0]
    Xn = [[0] * dS for _ in range(dT)]
    for l, c in enumerate(coef):
        if c:
            for i in range(dT):
                for j in range(dS):
                    Xn[i][j] = (Xn[i][j] + c * Xs[l][i][j]) % p
    return len(ns), Xn


def mat_inverse(A, p):
    n = len(A)
    M = [list(row) + [1 if i == j else 0 for j in range(n)] for i, row in enumerate(A)]
    E, piv = rref(M, p)
    assert piv == list(range(n)), "matrix not invertible"
    return [row[n:] for row in E]
