#!/usr/bin/env python3
"""
w133_r17_w2_recompute.py -- INDEPENDENT recomputation of the W2 witness.

Round 17, owner-w133. Purpose: discharge the open half of RULING 3 of
`orchestration/planner_msgs/cert_w133_provedS3.md` -- W1's numbers are double-sourced
(owner key script + the planner's from-scratch GF(5) rebuild), W2's are NOT.

INDEPENDENCE IS THE POINT, so this file deliberately shares no code and no model with
`w133_r11_qradp.py` / `w133_r14_heldout.py` / `w133_r15_key.py`, all of which build
PSL(2,11) as 2x2 matrices over GF(11) modulo +-I, canonicalised by min(m, -m).

Here the group is built as a PERMUTATION GROUP: PSL(2,11) acting by Moebius maps on the
12 points of the projective line P^1(GF(11)) = {0,...,10, oo}.  The named generator
matrices are pushed through that action and the group is generated by closure, so the
element set, the multiplication, and the identification of +-I are all obtained by a
different route.  A Cayley graph is determined up to isomorphism by (group, connection
set), and every quantity checked below is an isomorphism invariant, so agreement with
the matrix-model numbers is a genuine two-source agreement and not a re-run.

Faithfulness is not assumed: it is CHECKED (|image| = 660, not 1320) -- -I acts
trivially on P^1, so the permutation image of SL(2,11) is exactly PSL(2,11).

Red lines: no SAT, no exhaustive search over a large space.  The only searches are
(i) BFS from all 660 vertices, (ii) a common-neighbour count over all vertex pairs,
(iii) a restart-greedy induced-path builder with a hard wall-clock budget, whose output
is then certified from scratch by a separate O(L^2) check that does not trust the
builder.  Hard self-limit enforced below.

ONE product: the W2 independent-recomputation report.
"""
import sys, time, random

P = 11
INF = P                      # index of the point at infinity
NPTS = P + 1                 # |P^1(GF(11))| = 12
DEADLINE = time.time() + 420.0   # hard self-limit: 7 minutes total

fails = []
def check(cond, label, detail=""):
    ok = bool(cond)
    if not ok:
        fails.append(label)
    print("  %s  %s%s" % ("PASS" if ok else "FAIL", label,
                          ("   [%s]" % detail) if detail else ""))
    return ok

def guard():
    if time.time() > DEADLINE:
        print("\nHARD SELF-LIMIT REACHED -- aborting before completion.")
        sys.exit(2)

# ---------------------------------------------------------------- the group
def moebius(m):
    """Permutation of P^1(GF(11)) induced by the matrix m = (a,b,c,d), det 1.
    z |-> (az+b)/(cz+d), with the usual conventions at oo and at the pole."""
    a, b, c, d = (x % P for x in m)
    perm = [None] * NPTS
    for z in range(P):
        den = (c * z + d) % P
        num = (a * z + b) % P
        perm[z] = INF if den == 0 else (num * pow(den, P - 2, P)) % P
    # image of oo is a/c  (oo if c = 0)
    perm[INF] = INF if c % P == 0 else (a * pow(c, P - 2, P)) % P
    assert sorted(perm) == list(range(NPTS)), "moebius image is not a permutation"
    return tuple(perm)

def compose(p, q):
    """(p o q)(i) = p[q[i]] -- matches phi(m*k) = phi(m) o phi(k)."""
    return tuple(p[q[i]] for i in range(NPTS))

def inverse(p):
    inv = [0] * NPTS
    for i, j in enumerate(p):
        inv[j] = i
    return tuple(inv)

GEN_MATS = [(5, 0, 2, 9), (1, 5, 0, 1), (1, 6, 10, 6)]

print("=== W2 = Cay(PSL(2,11), S), INDEPENDENT permutation-model recomputation ===")
print("    (matrix model NOT used; group realised on P^1(GF(11)), 12 points)\n")

print("[1] the three named generator matrices lie in SL(2,11)")
for m in GEN_MATS:
    a, b, c, d = m
    check((a * d - b * c) % P == 1, "det[%d %d; %d %d] = 1 mod 11" % (a, b, c, d),
          "det=%d" % ((a * d - b * c) % P))

IDP = tuple(range(NPTS))
gen_perms = [moebius(m) for m in GEN_MATS]
print("\n[2] the generators act non-trivially and -I acts trivially")
for m, g in zip(GEN_MATS, gen_perms):
    check(g != IDP, "phi[%d %d; %d %d] != id" % m)
check(moebius((-1, 0, 0, -1)) == IDP, "phi(-I) = id  (so the image is PSL, not SL)")

# closure
S = set()
for g in gen_perms:
    S.add(g)
    S.add(inverse(g))
S = sorted(S)
frontier = [IDP]
elems = {IDP}
while frontier:
    guard()
    nxt = []
    for x in frontier:
        for s in S:
            y = compose(x, s)
            if y not in elems:
                elems.add(y)
                nxt.append(y)
    frontier = nxt
elems = sorted(elems)
idx = {e: i for i, e in enumerate(elems)}
n = len(elems)

print("\n[3] the generated group")
check(n == 660, "|<S>| = 660 = |PSL(2,11)|", "got %d" % n)
check(n != P * (P * P - 1), "DERIVED from the line above: image is NOT SL(2,11) (order 1320)", "not independent evidence; kept as a reading aid")
check(len(S) == 6, "|S| = 6 (three generators and their inverses, all distinct)", "got %d" % len(S))
check(IDP not in S, "identity is not in the connection set")
check(all(inverse(s) in S for s in S), "SELF-SATISFIED: S closed under inversion -- it was BUILT as {g, g^-1}", "carries no information; recorded as such per V7")

# ---------------------------------------------------------------- the graph
adj = [set() for _ in range(n)]
for e in elems:
    i = idx[e]
    for s in S:
        j = idx[compose(e, s)]
        if i != j:
            adj[i].add(j)
            adj[j].add(i)
deg = [len(a) for a in adj]
m_edges = sum(deg) // 2

print("\n[4] W2 as a graph")
check(min(deg) == 6 and max(deg) == 6, "6-regular", "deg range [%d,%d]" % (min(deg), max(deg)))
check(m_edges == 1980, "DERIVED from 6-regularity and n=660: 1980 edges", "got %d" % m_edges)

# triangle-freeness
tri = 0
for v in range(n):
    guard()
    nb = adj[v]
    for u in nb:
        if u > v:
            tri += len(nb & adj[u])
check(tri == 0, "triangle-free (0 edges inside any neighbourhood)", "triangle-incidences=%d" % tri)

# C4-freeness, strong form: no two distinct vertices with >= 2 common neighbours
worst = 0
bad = 0
for v in range(n):
    guard()
    cnt = {}
    for u in adj[v]:
        for w in adj[u]:
            if w != v:
                cnt[w] = cnt.get(w, 0) + 1
    for w, c in cnt.items():
        if c > worst:
            worst = c
        if c >= 2:
            bad += 1
check(bad == 0, "C4-free (strong form: no pair with 2 common neighbours)",
      "violating ordered pairs=%d, max common neighbours over pairs at distance 2 = %d" % (bad, worst))

# a-values: triangle-free + 6-regular => every neighbourhood is independent of size 6.
# Checked directly rather than inferred, so the assertion can actually fail.
sum_a = 0
a_min = 99
for v in range(n):
    nb = sorted(adj[v])
    internal = sum(1 for i, x in enumerate(nb) for y in nb[i + 1:] if y in adj[x])
    if internal != 0:
        check(False, "N(%d) independent" % v, "internal edges=%d" % internal)
        break
    sum_a += len(nb)
    a_min = min(a_min, len(nb))
check(sum_a == 6 * n, "sum of a(v) = 3960, so l(W2) = 6 exactly", "sum_a=%d, l=%s" % (sum_a, sum_a / n))
check(a_min == 6, "mu(W2) = min a = 6 >= 2 (Theorem G42's hypothesis holds)", "mu=%d" % a_min)
check(sum_a / n > 4, "l > 4 (the band hypothesis), computed not asserted", "l=%s" % (sum_a / n))

# ---------------------------------------------------------------- distances
def bfs(src):
    dist = [-1] * n
    dist[src] = 0
    q = [src]
    while q:
        nq = []
        for v in q:
            dv = dist[v] + 1
            for u in adj[v]:
                if dist[u] < 0:
                    dist[u] = dv
                    nq.append(u)
        q = nq
    return dist

ecc = []
dist_from_0 = None
for v in range(n):
    guard()
    d = bfs(v)
    if v == 0:
        dist_from_0 = d
    if min(d) < 0:
        check(False, "connected", "vertex %d unreachable from %d" % (d.index(-1), v))
        break
    ecc.append(max(d))
rad = min(ecc)
diam = max(ecc)
print("\n[5] distances -- eccentricity computed for ALL 660 vertices, not sampled")
check(len(ecc) == n, "connected (BFS reached all 660 from every vertex)", "%d BFS runs" % len(ecc))
check(rad == 5 and diam == 5, "rad = diam = 5", "rad=%d diam=%d" % (rad, diam))
check(len(set(ecc)) == 1, "every vertex has eccentricity 5 (vertex-transitivity corroborated)",
      "distinct eccentricities: %s" % sorted(set(ecc)))
check(diam <= rad + 2, "DERIVED from rad = diam = 5: diam <= rad + 2, the hard window is inhabited", "%d <= %d" % (diam, rad + 2))

# ---------------------------------------------------------------- G42's mechanism on W2
print("\n[6] Theorem G42's construction executed on W2: the CONSTRUCTED path")
far = [v for v in range(n) if dist_from_0[v] == 5]
check(len(far) > 0, "a geodesic of length d = rad = 5 exists from vertex 0", "%d vertices at distance 5" % len(far))

def build_geodesic(src, dst, dist):
    """dist = BFS distances from src; walk back from dst."""
    path = [dst]
    cur = dst
    while cur != src:
        for u in adj[cur]:
            if dist[u] == dist[cur] - 1:
                cur = u
                break
        path.append(cur)
    path.reverse()
    return path

constructed = None
for dst in far[:40]:
    guard()
    geo = build_geodesic(0, dst, dist_from_0)
    if len(geo) != 6:
        continue
    u0, u1, ud, ud1 = geo[0], geo[1], geo[-1], geo[-2]
    # x: a usable side-neighbour of u0. N(u0) is independent (triangle-free), so every
    # neighbour other than u1 is its own component of G[N(u0)] -- usable by definition.
    for x in adj[u0]:
        if x == u1 or x in geo:
            continue
        if len(adj[x]) < 4:
            continue                      # a(x) = 6 >= 4 here, but do not assume it
        for y in adj[ud]:
            if y == ud1 or y in geo or y == x:
                continue
            for w in adj[x]:
                if w == u0 or w in geo or w in (x, y):
                    continue
                cand = [w, x] + geo + [y]
                if len(set(cand)) != len(cand):
                    continue
                ok = True
                for i in range(len(cand)):
                    for j in range(i + 2, len(cand)):
                        if cand[j] in adj[cand[i]]:
                            ok = False
                            break
                    if not ok:
                        break
                if ok and all(cand[i + 1] in adj[cand[i]] for i in range(len(cand) - 1)):
                    constructed = cand
                    break
            if constructed: break
        if constructed: break
    if constructed: break

check(constructed is not None, "G41/G42's recipe (w, x, u_0..u_d, y) executes on W2")
if constructed:
    check(len(constructed) == 9, "the CONSTRUCTED path has exactly 9 vertices = d + 4 = rad + 4",
          "len=%d, d=%d, rad=%d" % (len(constructed), 5, rad))

# ---------------------------------------------------------------- the graph's own path
print("\n[7] the GRAPH's own longest induced path -- a LOWER BOUND, independently certified")
rng = random.Random(20260822)
best = []
restarts = 0
budget = min(DEADLINE, time.time() + 150.0)
while time.time() < budget and restarts < 4000:
    restarts += 1
    start = rng.randrange(n)
    path = [start]
    inpath = [False] * n
    inpath[start] = True
    cnt = [0] * n                     # cnt[u] = # path vertices adjacent to u
    for u in adj[start]:
        cnt[u] += 1
    ends = [0, 1]
    rng.shuffle(ends)
    for end in ends:
        while True:
            e = path[0] if end == 0 else path[-1]
            cands = [u for u in adj[e] if not inpath[u] and cnt[u] == 1]
            if not cands:
                break
            u = cands[rng.randrange(len(cands))]
            if end == 0:
                path.insert(0, u)
            else:
                path.append(u)
            inpath[u] = True
            for w in adj[u]:
                cnt[w] += 1
    if len(path) > len(best):
        best = list(path)

L = len(best)
# certification from scratch: nothing above is trusted
distinct = (len(set(best)) == L)
consec = all(best[i + 1] in adj[best[i]] for i in range(L - 1))
chords = sum(1 for i in range(L) for j in range(i + 2, L) if best[j] in adj[best[i]])
check(distinct, "the built vertex sequence has no repeats", "L=%d" % L)
check(consec, "consecutive vertices are adjacent")
check(chords == 0, "no chords: the sequence is an INDUCED path", "chords=%d" % chords)
check(L >= 168, "path(W2) >= 168 -- reproduces the single-sourced round-11 number",
      "certified induced path on %d vertices, from %d restarts" % (L, restarts))
if constructed:
    check(L > len(constructed), "the graph's path strictly exceeds the constructed one",
          "graph >= %d vs constructed = %d" % (L, len(constructed)))
check(L >= rad + 4, "DERIVED from L and rad: path(W2) >= rad + 4 = 9, the conjecture holds on W2",
      "%d >= %d" % (L, rad + 4))

# ---------------------------------------------------------------- verdict
print("\n=== PRODUCT: W2 independently recomputed, permutation model ===")
print("  n = %d   edges = %d   6-regular   triangle-free   C4-free" % (n, m_edges))
print("  l = sum_a/n = %d/%d = %s   mu = %d" % (sum_a, n, sum_a // n, a_min))
print("  rad = diam = %d   (eccentricity 5 at every one of the %d vertices)" % (rad, n))
print("  CONSTRUCTED path (G42's mechanism)  = %s vertices = rad + 4" %
      (len(constructed) if constructed else "NONE"))
print("  GRAPH's own induced path            >= %d vertices (certified chord-free)" % L)
print("  two numbers, never one tightness claim.")
print("\nchecks failed: %d" % len(fails))
for f in fails:
    print("  FAILED: %s" % f)
sys.exit(1 if fails else 0)
