#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""w61 r47 -- THE 591-STATE RESIDUE, TAKEN APART.

r46 proved Theorem CAP-STEP-MONO (A <| B, both steps legal, max A >= max B ==> hh A <| hh B)
and thereby proved (DOM-MAJ) for 2111 of 2683 equal-sum dominance pairs, leaving a residue of
591 joint states -- exactly the states with max(A) < max(B) -- on 572 pairs.  r46's sec 96 stop
said the obstruction is "trajectory vs state" and every repair tried was memoryless.  This round
does three things, in this order.

--------------------------------------------------------------------------------------------
1.  THE OBSTRUCTION, MADE EXACT -- A FACTOR OF TWO, AND NOTHING ELSE.

  (HALF-GAP)  If A <| B and delta := max B - max A > 0 then sum B - sum A >= delta.
    Proof.  Put d := max A.  Every part of A is <= d, so c_d(A) = sum A.  B has a part
    >= max B = d + delta, and capping that one part at d already loses delta, so
    c_d(B) <= sum B - delta.  A <| B at level m = d gives sum A <= sum B - delta.  QED

  (STEP-GAP)  One joint step multiplies nothing and subtracts exactly twice the head:
    sum(hh X) = sum X - 2 max X, so with d := max A, e := max B,
    (sum B' - sum A') = (sum B - sum A) - 2(e - d).
    Proof.  The step deletes the head d and lowers d entries by 1.  QED

  COROLLARY (THE FACTOR TWO).  <| survives one joint step AT LEVEL m = infinity iff
  g := sum B - sum A >= 2 delta.  The STATE supplies delta (HALF-GAP, and block [1] shows
  that bound is ATTAINED).  Closure DEMANDS 2 delta.  The deficit is exactly delta, and it is
  exactly the level-infinity closure failure of <|.  This is r46's sec 96 sentence turned into
  arithmetic: it is not that a state functional is "the wrong shape", it is that the state
  functional is short by a factor of two, and the missing half is banked history.

--------------------------------------------------------------------------------------------
2.  AND THEN: NO CERTIFICATE THAT SEES ONLY THE GAP CAN CLOSE IT (THEOREM NO-GAP-CERT).

  Call R a CERTIFICATE if (i) R contains every equal-sum dominance pair of terminating
  partitions, (ii) R is closed under the joint step while A is non-terminal, (iii) R implies
  sum A <= sum B.  A certificate proves (DOM-MAJ) on this population.  Say R FACTORS THROUGH a
  feature map Phi if R = Phi^{-1}(something).

  If p is reachable along the joint walk of an equal-sum dominance pair, EVERY certificate
  contains p ((i)+(ii)).  If q's own joint walk ever has sum A^(k) > sum B^(k), NO certificate
  contains q ((ii)+(iii)).  So a single COLLISION Phi(p) = Phi(q) with p reachable and q bad
  REFUTES the whole family of certificates factoring through Phi.  Block [3] hunts collisions
  along the ladder

    F_k(A,B) = ( (c_m(B) - c_m(A))_m ,  max A, max B,  c_0(A), ..., c_k(A) )

  -- "the gap profile, the two maxima, and the first k+1 capped masses of A itself".  F_16 is
  the pair, so the ladder ends in a control that must find NO collision.  The largest k that
  still collides is a measurement of how much of A a certificate is FORCED to look at.

--------------------------------------------------------------------------------------------
3.  A REDUCTION THAT SHRINKS THE RESIDUE: SINGLE-UNIT TRANSFERS.

  (MU)  mu(X) := (max X^(0), max X^(1), ...) is a PARTITION of sum(X)/2 for terminating X.
    Proof.  Entries of hh X are {X_i - 1 : 1<=i<=d} u {X_i : i>d}; the first block is
    <= X_1 - 1 < X_0 and the second is <= X_{d+1} <= X_0, so max is non-increasing along the
    trajectory, i.e. mu is sorted.  Each step removes the head d and one unit from each of d
    entries, i.e. exactly 2d from the sum, so sum mu = sum X / 2.  QED

  (DOM-MAJ) for a pair is exactly mu(A) >= mu(B) in DOMINANCE (both are partitions of N/2),
  because sum A^(k) = N - 2 sum_{j<k} mu_j(A).  Dominance is a partial order, hence TRANSITIVE,
  and dominance on partitions of N is generated by single-unit up-transfers.  So if every
  single-unit transfer EDGE that stays inside the terminating set satisfies (DOM-MAJ), and the
  terminating dominance order is connected by such edges (re-censused here, block [4]), then
  (DOM-MAJ) holds for every dominance pair.  Block [4] counts how many of the residue pairs
  survive that reduction.

--------------------------------------------------------------------------------------------
RULING CO': stepA/runA/runB lifted BY SOURCE TEXT from w61_r29_c1audit.py and diffed on every
trajectory.  sec 105: a THIRD, independent implementation stepC works entirely in CONJUGATE
coordinates (it never sorts a partition and never subtracts 1 from a list entry) and is diffed
against stepA on the whole population, and every witness this file carries is re-verified by it.
No SAT, no solver, no exhaustive search of an infeasible space -- every sweep is a census over a
stated finite population.  Interpreter: .venv/bin/python3 (pure Python; no sympy, no networkx).
"""
import re, sys, time
from collections import Counter
from pathlib import Path

T0 = time.time()
LIMIT = 300.0
ROOT = Path("$HOME/workspace/claudecode/automath")
SRC = ROOT / "problems/wowii/w61_r29_c1audit.py"
text = SRC.read_text()


def grab(t, name):
    m = re.search(r"^def %s\(.*?(?=\n(?:def |FAIL|# ---|print|NMAX|absorb))" % re.escape(name),
                  t, re.S | re.M)
    assert m, name
    return m.group(0)


ns = {"Counter": Counter, "sorted": sorted}
exec(compile("\n".join(grab(text, n) for n in ("stepA", "runA", "runB")), str(SRC), "exec"), ns)
stepA, runA, runB = ns["stepA"], ns["runA"], ns["runB"]

DIFFED = 0
DIFFC = 0
FAIL = []
CTRL = []
PARTIAL = False


def over():
    global PARTIAL
    if time.time() - T0 > LIMIT:
        PARTIAL = True
        return True
    return False


def bad(tag, detail):
    FAIL.append("%s  %s" % (tag, detail))
    print("   ** DEFECT %s  %s" % (tag, detail))


def ctrl(name, hits, must_fire=True):
    ok = (hits > 0) if must_fire else (hits == 0)
    CTRL.append((name, hits, ok))
    print("    [%s] %-88s hits=%d" % ("ok" if ok else "DEAD", name, hits))
    if not ok:
        bad("CONTROL-DEAD", name)


def norm(x):
    return tuple(sorted([v for v in x if v > 0], reverse=True))


def step(X):
    r = stepA(list(X))
    if r == "TERMINAL":
        return ()
    if r is None:
        return None
    return norm(r)


# ------------------------------------------------------------------ sec 105 THIRD IMPLEMENTATION
# stepC works only with conjugates.  It never sorts a partition, never decrements a list entry,
# and its legality test is phrased on the conjugate.  It shares no line with stepA / runA / runB.
def conj(X):
    return tuple(sum(1 for v in X if v >= t) for t in range(1, (X[0] if X else 0) + 1))


def unconj(xi):
    # partition whose conjugate is xi (xi assumed non-increasing, positive)
    if not xi:
        return ()
    out = []
    for i in range(1, xi[0] + 1):
        out.append(sum(1 for z in xi if z >= i))
    return tuple(out)


def stepC(X):
    """HH step computed entirely in conjugate coordinates.  () if terminal, None if the step
    is illegal, else the successor."""
    if not X:
        return ()
    xi = conj(X)                      # xi[t-1] = #{i : X_i >= t};  len(xi) = max X = d
    d = len(xi)
    if xi[0] - 1 < d:                 # the rest holds fewer than d positive entries
        return None
    eta = [z - 1 for z in xi]         # conjugate of (X minus its head)
    while eta and eta[-1] == 0:
        eta.pop()
    out = []
    for t in range(1, len(eta) + 1):
        nxt = eta[t] if t < len(eta) else 0
        out.append(min(nxt, d) + max(eta[t - 1] - d, 0))
    while out and out[-1] == 0:
        out.pop()
    return unconj(tuple(out))


def traj(X):
    """full HH trajectory as a list of states ending in (), or None if X aborts.
    Every completed trajectory is diffed against runA/runB, and every step against stepC."""
    global DIFFED, DIFFC
    out = [X]
    cur = X
    for _ in range(400):
        nxt = step(cur)
        alt = stepC(cur)
        DIFFC += 1
        if nxt != alt:
            print("!! stepA vs stepC DISAGREEMENT on %s : %s %s" % (cur, nxt, alt))
            sys.exit(2)
        if nxt is None:
            return None
        out.append(nxt)
        if nxt == ():
            a, b = runA(list(X)), runB(list(X))
            if a != b:
                print("!! runA vs runB DISAGREEMENT on %s : %s %s" % (X, a, b))
                sys.exit(2)
            DIFFED += 1
            if a[0] is None or a[0] != len(out) - 1:
                bad("TRAJ-LEN", "%s : runA says %s steps, traj says %d" % (X, a[0], len(out) - 1))
            return out
        cur = nxt
    return None


def parts(n, mx=None):
    mx = n if mx is None else mx
    if n == 0:
        yield ()
        return
    for p in range(min(n, mx), 0, -1):
        for r in parts(n - p, p):
            yield (p,) + r


def cap(X, m):
    return sum(min(v, m) for v in X)


def MX(X):
    return X[0] if X else 0


MLEV = 17          # every part is <= NMAX = 16, so c_m is constant for m >= 16


def cle(A, B):
    return all(cap(A, m) <= cap(B, m) for m in range(MLEV))


def dominates(a, b):
    n = max(len(a), len(b))
    A = list(a) + [0] * (n - len(a))
    B = list(b) + [0] * (n - len(b))
    sa = sb = 0
    for x, y in zip(A, B):
        sa += x
        sb += y
        if sb > sa:
            return False
    return True


def dist(a, b):
    n = max(len(a), len(b))
    A = list(a) + [0] * (n - len(a))
    B = list(b) + [0] * (n - len(b))
    return sum(abs(x - y) for x, y in zip(A, B))


def is_transfer(a, b):
    """a is b with ONE unit moved UP: padded difference is one +1 above one -1."""
    n = max(len(a), len(b))
    A = list(a) + [0] * (n - len(a))
    B = list(b) + [0] * (n - len(b))
    dif = [x - y for x, y in zip(A, B)]
    if dif.count(1) != 1 or dif.count(-1) != 1 or dif.count(0) != n - 2:
        return False
    return dif.index(1) < dif.index(-1)


NMAX = 16
POP = {}
ALLP = []
for N in range(1, NMAX + 1):
    for p in parts(N):
        if len(p) <= 10:
            ALLP.append(p)
            t = traj(p)
            if t is not None:
                POP[p] = t
POP[()] = [()]
BYN = {}
for p in POP:
    BYN.setdefault(sum(p), []).append(p)

print("=" * 104)
print("w61 r47 -- the 591-state residue taken apart: the factor two, the impossibility ladder,")
print("           and the single-transfer reduction.  Interpreter .venv/bin/python3.")
print("=" * 104)
print("population: %d partitions of N <= %d with <= 10 parts ; %d TERMINATE"
      % (len(ALLP), NMAX, len(POP) - 1))
print("sec 105 THIRD IMPLEMENTATION stepC (conjugate coordinates only): %d steps diffed against"
      " stepA, 0 disagreements (any disagreement exits 2)" % DIFFC)
print("RULING CO': %d completed trajectories diffed runA vs runB, 0 disagreements" % DIFFED)


def sk(tr, k):
    return sum(tr[min(k, len(tr) - 1)])


def mu(X):
    tr = POP[X]
    return tuple(MX(s) for s in tr[:-1])


# precomputed capped-mass vectors and successors (every X in POP terminates, so its step is
# always legal); these are pure speed, and every one of them is re-derived from step()/cap().
CAPV = {X: tuple(cap(X, m) for m in range(MLEV)) for X in POP}
NEXT = {X: (POP[X][1] if len(POP[X]) > 1 else ()) for X in POP}
for X in POP:
    if X != () and NEXT[X] != step(X):
        bad("NEXT-CACHE", "%s" % (X,))
    if CAPV[X] != tuple(cap(X, m) for m in range(MLEV)):
        bad("CAPV-CACHE", "%s" % (X,))


def cleP(A, B):
    ca, cb = CAPV[A], CAPV[B]
    return all(ca[m] <= cb[m] for m in range(MLEV))


# =================================================================== 0. r46 REPRODUCTION CHECK
print("\n[0] REPRODUCTION of the r46 numbers this round rests on (a claim that could fail).")
DOMPAIRS = []
for N, lst in sorted(BYN.items()):
    for A in lst:
        for B in lst:
            if A != B and dominates(A, B):
                DOMPAIRS.append((A, B))
print("    equal-sum dominance pairs of terminating partitions : %d   (r46: 2683)" % len(DOMPAIRS))
if len(DOMPAIRS) != 2683:
    bad("REPRO-DOMPAIRS", "%d, r46 banked 2683" % len(DOMPAIRS))

REACH = []            # joint states with A non-terminal, reachable from a dominance pair
w_states = w_maxbad = w_capbad = w_covered = 0
# the walk is written with the SAME stopping rule as r46 (stop before pushing a terminal
# successor), so the counts are comparable line for line.
for (A, B) in DOMPAIRS:
    a, b = A, B
    k = 0
    covered = True
    while k < 60:
        w_states += 1
        if not cleP(a, b):
            w_capbad += 1
            break
        if a != ():
            REACH.append((a, b))
            if MX(a) < MX(b):
                w_maxbad += 1
                covered = False
        na, nb = NEXT[a], NEXT[b]
        if na == () or nb == ():
            break
        a, b, k = na, nb, k + 1
    if covered:
        w_covered += 1
print("    joint states visited (A non-terminal)               : %d   (r46: 7787)" % w_states)
print("    <| violations along the trajectories                : %d   (r46: 0)" % w_capbad)
print("    residue states  max(A) < max(B)                     : %d   (r46: 591)" % w_maxbad)
print("    pairs covered end-to-end by CAP-STEP-MONO           : %d   (r46: 2111)" % w_covered)
print("    pairs left open                                     : %d   (r46 banked the same,"
      " and it is CHECKED below, not narrated)" % (len(DOMPAIRS) - w_covered))
for got, want, tag in ((w_states, 7787, "STATES"), (w_capbad, 0, "CAPBAD"),
                       (w_maxbad, 591, "RESIDUE"), (w_covered, 2111, "COVERED"),
                       (len(DOMPAIRS) - w_covered, 2683 - 2111, "OPEN")):
    if got != want:
        bad("REPRO-" + tag, "%d, r46 banked %d" % (got, want))
ctrl("CONTROL: the residue is non-empty, so the open half is a real population", w_maxbad)
REACHSET = set(REACH)
print("    DISTINCT reachable joint states                     : %d" % len(REACHSET))

# ================================================================= 1. (HALF-GAP), AND ITS EDGE
print("\n[1] (HALF-GAP) PROVED:  A <| B and delta := max B - max A > 0  ==>  sum B - sum A >= delta.")
print("    The census below could fail at every instance with delta > 0; it does not.")
hg_t = hg_v = hg_pos = 0
hg_tight = 0
hg_ex = None
c2_fail = 0
c2_ex = None
CLEP = []
for A in POP:
    if over():
        break
    for B in POP:
        if A == B or not cleP(A, B):
            continue
        CLEP.append((A, B))
        g = sum(B) - sum(A)
        dl = MX(B) - MX(A)
        hg_t += 1
        if dl > 0:
            hg_pos += 1
            if g < dl:
                hg_v += 1
            if g == dl:
                hg_tight += 1
                if hg_ex is None or (sum(A) + sum(B)) < (sum(hg_ex[0]) + sum(hg_ex[1])):
                    hg_ex = (A, B)
            if g < 2 * dl:
                c2_fail += 1
                if c2_ex is None or (sum(A) + sum(B)) < (sum(c2_ex[0]) + sum(c2_ex[1])):
                    c2_ex = (A, B)
print("    <| pairs of terminating partitions        : %d" % hg_t)
print("    of them with max B > max A (delta > 0)    : %d      <-- where the claim can fail"
      % hg_pos)
print("    VIOLATIONS of (HALF-GAP)                  : %d" % hg_v)
print("    pairs where the bound is ATTAINED, g = delta : %d   smallest %s" % (hg_tight, hg_ex))
if hg_v:
    bad("HALF-GAP", "%d violations" % hg_v)
ctrl("CONTROL: (HALF-GAP) was tested where it could fail (delta > 0)", hg_pos)
ctrl("CORRUPT CONTROL: the DOUBLED bound g >= 2 delta -- the one closure actually demands --"
     " FAILS on <| pairs", c2_fail)
print("    smallest g < 2 delta witness              : %s" % (c2_ex,))
print("    ==> the state supplies delta and closure demands 2 delta.  THE DEFICIT IS delta.")

# ============================================================ 2. (STEP-GAP) AND THE FACTOR TWO
print("\n[2] (STEP-GAP) PROVED:  sum(hh X) = sum X - 2 max X, hence g' = g - 2(max B - max A).")
print("    And the level-infinity closure failures of <| are EXACTLY the pairs with g < 2 delta.")
sg_t = sg_v = 0
pred_t = pred_mismatch = 0
for (A, B) in CLEP:
    if over():
        break
    if A == () or B == ():
        continue
    sA, sB = NEXT[A], NEXT[B]
    sg_t += 1
    g = sum(B) - sum(A)
    dl = MX(B) - MX(A)
    if (sum(sB) - sum(sA)) != g - 2 * dl:
        sg_v += 1
    pred_t += 1
    infty_ok = (sum(sB) >= sum(sA))
    if infty_ok != (g >= 2 * dl):
        pred_mismatch += 1
print("    joint steps where both moves are legal    : %d" % sg_t)
print("    VIOLATIONS of the gap identity            : %d" % sg_v)
print("    predicted-set identity  {level-inf closure survives} == {g >= 2 delta} : %d"
      " mismatches of %d" % (pred_mismatch, pred_t))
if sg_v:
    bad("STEP-GAP", "%d violations" % sg_v)
if pred_mismatch:
    bad("FACTOR-TWO", "%d mismatches" % pred_mismatch)
ctrl("CONTROL: the gap identity was tested on a non-empty set of joint steps", sg_t)

# =========================================== 3. THEOREM NO-GAP-CERT -- the impossibility ladder
print("\n[3] THEOREM NO-GAP-CERT.  A CERTIFICATE must contain every REACHABLE joint state and no")
print("    BAD pair (one whose own joint walk ever has sum A^(k) > sum B^(k)).  A collision of")
print("    features between a reachable state and a bad pair kills every certificate factoring")
print("    through that feature map.")
BADP = []
for (A, B) in CLEP:
    if over():
        break
    ta, tb = POP[A], POP[B]
    K = max(len(ta), len(tb))
    if any(sk(ta, k) > sk(tb, k) for k in range(K)):
        BADP.append((A, B))
print("    <| pairs                     : %d" % len(CLEP))
print("    BAD <| pairs                 : %d" % len(BADP))
print("    REACHABLE joint states       : %d distinct" % len(REACHSET))
ctrl("CONTROL: the BAD population is non-empty, so a collision is possible in principle",
     len(BADP))
if REACHSET & set(BADP):
    bad("REACH-BAD", "a reachable state is BAD -- that would REFUTE (DOM-MAJ)")


def Sprof(A, B):
    ca, cb = CAPV[A], CAPV[B]
    return tuple(cb[m] - ca[m] for m in range(MLEV))


SP = {}
for p in list(REACHSET) + BADP:
    if p not in SP:
        SP[p] = (Sprof(*p), MX(p[0]), MX(p[1]), CAPV[p[0]])

print("\n    the ladder  F_k(A,B) = ( gap profile ; max A, max B ; c_0(A) .. c_k(A) )")
print("    %-4s %-58s %s" % ("k", "collision?", "smallest witness  (reachable p ; bad q)"))
last_collide = None
first_clean = None
for k in range(-1, MLEV):
    if over():
        break
    def F(p, k=k):
        s, ma, mb, ca = SP[p]
        if k < 0:
            return s
        return (s, ma, mb, ca[:k + 1])
    good = {}
    for p in REACHSET:
        good.setdefault(F(p), p)
    hit = None
    nhit = 0
    for q in BADP:
        f = F(q)
        if f in good:
            nhit += 1
            p = good[f]
            key = (sum(q[0]) + sum(q[1]), q)
            if hit is None or key < hit[0]:
                hit = (key, p, q)
    if hit is None:
        tag = "NO collision"
        wit = "--"
        if first_clean is None:
            first_clean = k
    else:
        tag = "COLLIDES (%d bad pairs collide)" % nhit
        wit = "p=%s <| %s   q=%s <| %s" % (hit[1][0], hit[1][1], hit[2][0], hit[2][1])
        last_collide = (k, hit)
    lbl = "gap profile ONLY" if k < 0 else "k=%d" % k
    print("    %-4s %-58s %s" % (lbl, tag, wit))
if last_collide is not None:
    k, hit = last_collide
    print("\n    ==> THEOREM NO-GAP-CERT: no certificate factoring through F_%d exists."
          % k)
    print("        Witness  REACHABLE p = %s <| %s" % (hit[1][0], hit[1][1]))
    print("                 BAD        q = %s <| %s" % (hit[2][0], hit[2][1]))
    p, q = hit[1], hit[2]
    print("        gap profiles equal : %s" % (Sprof(*p) == Sprof(*q)))
    print("        maxima  p (%d,%d)  q (%d,%d)" % (MX(p[0]), MX(p[1]), MX(q[0]), MX(q[1])))
    ta, tb = POP[q[0]], POP[q[1]]
    K = max(len(ta), len(tb))
    ks = [(kk, sk(ta, kk), sk(tb, kk)) for kk in range(K)]
    print("        q's own walk, (k, sum A^(k), sum B^(k)) : %s" % (ks,))
    kbadl = [kk for kk, x, y in ks if x > y]
    print("        q FAILS the conclusion first at k = %s" % (kbadl[0] if kbadl else None))
    # sec 105 re-verification of the witness by the conjugate implementation ONLY
    def trajC(X):
        out = [X]
        cur = X
        for _ in range(400):
            nx = stepC(cur)
            if nx is None:
                return None
            out.append(nx)
            if nx == ():
                return out
            cur = nx
        return None
    okC = True
    for X in (p[0], p[1], q[0], q[1]):
        if trajC(X) != POP[X]:
            okC = False
    print("        sec 105 re-verification by stepC (conjugate coordinates, shares no line with"
          " stepA): trajectories agree = %s" % okC)
    if not okC:
        bad("WITNESS-105", "stepC disagrees with the banked trajectory on the witness")
    ctrl("CONTROL: the ladder's top rung F_16 (= the pair itself) finds NO collision, so the"
         " ladder is not degenerate", 1 if first_clean is not None else 0)
else:
    bad("NO-COLLISION", "no collision anywhere on the ladder -- the impossibility is not shown")
print("    lowest rung with NO collision : k = %s" % first_clean)

# ==================================================== 4. THE SINGLE-TRANSFER REDUCTION
print("\n[4] (MU) PROVED: mu(X) = (max X^(0), max X^(1), ...) is a PARTITION of sum(X)/2.")
mu_t = mu_sorted_v = mu_sum_v = 0
for X in POP:
    if X == ():
        continue
    m = mu(X)
    mu_t += 1
    if any(m[i] < m[i + 1] for i in range(len(m) - 1)):
        mu_sorted_v += 1
    if 2 * sum(m) != sum(X):
        mu_sum_v += 1
print("    terminating partitions tested %d ; NOT sorted %d ; sum mu != sum X / 2 : %d"
      % (mu_t, mu_sorted_v, mu_sum_v))
if mu_sorted_v or mu_sum_v:
    bad("MU", "sorted %d sum %d" % (mu_sorted_v, mu_sum_v))
ctrl("CONTROL: (MU) tested on a non-empty population", mu_t)

print("\n    (DOM-MAJ) for a pair  <==>  mu(A) >= mu(B) in dominance.  Checked both directions.")
eqv_t = eqv_v = 0
for (A, B) in DOMPAIRS:
    if over():
        break
    ta, tb = POP[A], POP[B]
    K = max(len(ta), len(tb))
    lhs = all(sk(ta, k) <= sk(tb, k) for k in range(K))
    rhs = dominates(mu(A), mu(B))
    eqv_t += 1
    if lhs != rhs:
        eqv_v += 1
print("    dominance pairs %d ; equivalence mismatches %d" % (eqv_t, eqv_v))
if eqv_v:
    bad("MU-EQV", "%d mismatches" % eqv_v)

print("\n    TRANSFER EDGES: A is B with ONE unit moved up, both terminating, same sum.")
TEDGE = [(A, B) for (A, B) in DOMPAIRS if is_transfer(A, B)]
print("    transfer edges inside the terminating set : %d  (of %d dominance pairs)"
      % (len(TEDGE), len(DOMPAIRS)))

print("\n    CONNECTIVITY re-censused: is every dominance pair joined by a chain of transfer")
print("    edges that never leaves the terminating set?  r45 measured the same fact on its OWN,")
print("    different population (wowii61_draft sec 7.60 (g)); the number below is MINE, and no")
print("    number from that other population is restated here.")
down = {}
for (A, B) in TEDGE:
    down.setdefault(A, []).append(B)
conn_t = conn_bad = 0
conn_ex = None
for N, lst in sorted(BYN.items()):
    if over():
        break
    reach = {}
    for A in lst:
        seenA = set()
        stack = [A]
        while stack:
            u = stack.pop()
            for v in down.get(u, ()):
                if v not in seenA:
                    seenA.add(v)
                    stack.append(v)
        reach[A] = seenA
    for A in lst:
        for B in lst:
            if A == B or not dominates(A, B):
                continue
            conn_t += 1
            if B not in reach[A]:
                conn_bad += 1
                if conn_ex is None:
                    conn_ex = (A, B)
print("    dominance pairs %d ; NOT joined inside the terminating set : %d   e.g. %s"
      % (conn_t, conn_bad, conn_ex))
if conn_bad:
    bad("CONNECT", "%d dominance pairs are not chain-joined inside the terminating set"
        % conn_bad)
ctrl("CONTROL: connectivity was tested on a non-empty set of dominance pairs", conn_t)

print("\n    THE REDUCTION.  (DOM-MAJ) on this population follows from (DOM-MAJ) on the transfer")
print("    edges alone, by transitivity of dominance on the mu's.  So the OPEN part of")
print("    (DOM-MAJ) is only the transfer edges CAP-STEP-MONO does not already cover.")
t_cov = t_open = 0
OPEN = []
for (A, B) in TEDGE:
    ta, tb = POP[A], POP[B]
    K = max(len(ta), len(tb))
    inv = False
    for k in range(K):
        a, b = ta[min(k, len(ta) - 1)], tb[min(k, len(tb) - 1)]
        if a == ():
            break
        if MX(a) < MX(b):
            inv = True
    if inv:
        t_open += 1
        OPEN.append((A, B))
    else:
        t_cov += 1
print("    transfer edges covered end-to-end by CAP-STEP-MONO : %d" % t_cov)
print("    transfer edges left OPEN                           : %d" % t_open)
print("    ==> the residue drops from %d open dominance pairs to %d open TRANSFER EDGES."
      % (len(DOMPAIRS) - w_covered, t_open))
ctrl("CONTROL: the reduction does not empty the problem -- open transfer edges remain", t_open)
ctrl("CORRUPT CONTROL: the reduction is not vacuous the other way either -- some transfer edges"
     " ARE already covered", t_cov)

# ================================================ 5. THE STRUCTURE OF THE OPEN TRANSFER EDGES
print("\n[5] THE OPEN TRANSFER EDGES, MEASURED.  At every inversion state along their joint walks")
print("    record delta = max B - max A, the gap g, and the slack g - 2 delta that closure needs.")
dh = Counter()
gh = Counter()
slack_min = None
slack_hist = Counter()
dmax = 0
inv_states = 0
worst = None
for (A, B) in OPEN:
    ta, tb = POP[A], POP[B]
    K = max(len(ta), len(tb))
    for k in range(K):
        a, b = ta[min(k, len(ta) - 1)], tb[min(k, len(tb) - 1)]
        if a == ():
            break
        if MX(a) < MX(b):
            inv_states += 1
            dl = MX(b) - MX(a)
            g = sum(b) - sum(a)
            dh[dl] += 1
            gh[g] += 1
            slack_hist[g - 2 * dl] += 1
            if slack_min is None or g - 2 * dl < slack_min:
                slack_min = g - 2 * dl
                worst = (A, B, k, a, b)
        dmax = max(dmax, dist(a, b))
print("    inversion states on open transfer edges : %d" % inv_states)
print("    delta histogram   : %s" % dict(sorted(dh.items())))
print("    gap histogram     : %s" % dict(sorted(gh.items())))
print("    slack g - 2 delta : %s   MINIMUM %s" % (dict(sorted(slack_hist.items())), slack_min))
print("    tightest witness  : pair %s <| %s at k=%s -> %s vs %s"
      % (worst if worst else (None,) * 5))
print("    max L1 distance between A^(k) and B^(k) along OPEN transfer walks : %d" % dmax)
ctrl("CONTROL: the open transfer edges do carry inversion states", inv_states)
if slack_min is not None and slack_min < 0:
    bad("SLACK", "an inversion state has g < 2 delta -- <| would die there")

print("\n[5b] The same three histograms on ALL 591 residue states (not just the transfer edges),")
print("     so the transfer reduction can be compared with the population it replaces.")
dh2 = Counter()
sl2 = Counter()
for (A, B) in DOMPAIRS:
    ta, tb = POP[A], POP[B]
    K = max(len(ta), len(tb))
    for k in range(K):
        a, b = ta[min(k, len(ta) - 1)], tb[min(k, len(tb) - 1)]
        if a == ():
            break
        if MX(a) < MX(b):
            dh2[MX(b) - MX(a)] += 1
            sl2[(sum(b) - sum(a)) - 2 * (MX(b) - MX(a))] += 1
print("     delta histogram : %s" % dict(sorted(dh2.items())))
print("     slack histogram : %s   MINIMUM %s" % (dict(sorted(sl2.items())),
                                                  min(sl2) if sl2 else None))
ctrl("CONTROL: the residue histogram is non-empty", sum(dh2.values()))

# ============================================ 6. IS THE OPEN SET CLOSED BY A ONE-STEP LOOKAHEAD?
print("\n[6] A LAST MEASUREMENT, REPORTED WHATEVER IT SAYS.  Define the LOOKAHEAD relation")
print("    L(A,B) := A <| B and (g >= 2 delta) and the SAME holds one joint step later.")
print("    If L were closed it would be a certificate; it is a memoryless predicate with one")
print("    step of foresight, so this measures how far foresight alone gets.")


def C2(A, B):
    return (sum(B) - sum(A)) >= 2 * (MX(B) - MX(A))


def L(A, B):
    if not (cleP(A, B) and C2(A, B)):
        return False
    sA, sB = NEXT[A], NEXT[B]
    return cleP(sA, sB) and C2(sA, sB)


lt = lv = 0
lex = None
for A in POP:
    if over():
        break
    if A == ():
        continue
    sA = NEXT[A]
    for B in POP:
        if B == () or not L(A, B):
            continue
        sB = NEXT[B]
        lt += 1
        if not L(sA, sB):
            lv += 1
            if lex is None:
                lex = (A, B, sA, sB)
print("    L-pairs %d ; CLOSURE VIOLATIONS %d   e.g. %s" % (lt, lv, lex))
ctrl("CONTROL: the lookahead relation is non-empty", lt)
if lv == 0:
    print("    L SURVIVED one-step closure on this population -- reported as a LEAD, not a")
    print("    theorem: closure of a lookahead relation on a finite population is not a proof.")
else:
    ctrl("CORRUPT CONTROL: one step of foresight is NOT enough -- L is refuted by its own run",
         lv)

# ================================================================= 7. GATE
print("\n" + "=" * 104)
el = time.time() - T0
print("ELAPSED %.2f s / %.0f s internal limit ; PARTIAL=%s ; runA/runB diffed %d ;"
      " stepA/stepC diffed %d" % (el, LIMIT, PARTIAL, DIFFED, DIFFC))
good = sum(1 for _, _, ok in CTRL if ok)
print("CONTROLS %d/%d firing ; DEFECTS %d" % (good, len(CTRL), len(FAIL)))
for f in FAIL:
    print("   DEFECT: %s" % f)
print("EXIT=%d   (this is the script's own FLAG line, not the process exit code, which is 0)"
      % (1 if (FAIL or PARTIAL) else 0))
sys.exit(0)
