#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""w61 r46 -- E47 HARVESTED (it is a BURNED call: no `content`, 64000 completion tokens spent
in hidden reasoning).  Its ONE construction -- a conjugate-coordinate reading of the HH step --
is REBUILT here from scratch, its coordinates are RE-CHOSEN (doctrine sec 97), and the
re-choice turns its central (and UNSOUND) claim into a proved theorem that is strictly
stronger than the one it was reaching for.

WHAT E47's TRACE GOT WRONG, AND WHY IT MATTERS.  The trace asserts, repeatedly and
load-bearingly, "dominance <=> conjugate pointwise <=".  That is FALSE: pointwise <= on
conjugates is Young-diagram CONTAINMENT (lam_i <= gam_i for every i), and for two partitions
of the SAME integer it forces equality.  Its "plateau theorem" (its DELIVERABLE 1) is deduced
from that equivalence and therefore does not stand as written.  Block [0d] of this file
exhibits the falsity as a census, so the correction is measured and not asserted.

THE RE-CHOICE.  Dominance is the PREFIX-SUM order on conjugates, not the pointwise one, and
the prefix sums of a conjugate have a primal name:

    c_m(X) := sum_i min(X_i, m)   ("the mass of X capped at level m")   = sum_{t<=m} conj(X)_t

    X <| Y  :<=>  c_m(X) <= c_m(Y) for every m >= 0.

  * for EQUAL sums, X <| Y is exactly X >= Y in dominance  (block [2a])
  * X <| Y always gives sum(X) <= sum(Y)  (m large), which is the (DOM-MAJ) conclusion at k=0
  * <| is the order generated by "delete a unit" and "move a unit UP"  (block [2c])

so <| is dominance extended to unequal sums in the one way that keeps the conclusion of
(DOM-MAJ) as its m = infinity instance.  Everything below is in these coordinates.

--------------------------------------------------------------------------------------
THE DICTIONARY (mine; E47's construction rebuilt, re-derived, re-verified)

  hh(X) = remove the head d := X[0], then subtract 1 from the d largest remaining entries.
  Write  rho_{m+1}(X) := #{i >= 1 : X_i >= m+1}  (the count EXCLUDING the head).

    (CAP-STEP)   c_m(hh X) = c_m(X) - d - min(d,m) + min(rho_{m+1}(X), d).

  Derivation.  c_m(hh X) = sum_{1<=i<=d} min(X_i - 1, m) + sum_{i>d} min(X_i, m).  The block
  entries are >= 1 (legality), so min(X_i - 1, m) = min(X_i, m+1) - 1, giving
  c_m(hh X) = [sum_{i>=1} min(X_i,m)] - d + #{1<=i<=d : X_i >= m+1}
            = [c_m(X) - min(d,m)] - d + min(rho_{m+1}(X), d).   QED

  Two consequences used below, both one-liners from (CAP-STEP):
    (CAP-DROP)   hh(X) <| X   for every X whose step is legal.
    (CAP-TAIL)   c_m(rest X) = c_m(X) - min(d, m),  where rest X = X minus its head.

--------------------------------------------------------------------------------------
THE TWO LEMMAS AND THE THEOREM (all mine, all PROVED, all censused below)

  Om_d(Z) := subtract 1 from the d largest entries of Z (legal iff Z has >= d positive ones).
  Its conjugate is  conj(Om_d Z)_t = min(zeta_{t+1}, d) + (zeta_t - d)^+  with zeta = conj Z,
  and since min(u,d) + (u-d)^+ = u the prefix sums telescope to

    (OM-CAP)   c_m(Om_d Z) = c_m(Z) - min(zeta_1, d) + min(zeta_{m+1}, d).

  LEMMA OM-MONO (PROVED).  If X <| Y and both have >= d positive entries then Om_d X <| Om_d Y.
    Proof.  By (OM-CAP) with min(xi_1,d) = min(eta_1,d) = d, the claim is
      c_m(X) + min(xi_{m+1}, d)  <=  c_m(Y) + min(eta_{m+1}, d).
    X <| Y at level m+1 reads c_m(X) + xi_{m+1} <= c_m(Y) + eta_{m+1}, i.e.
      c_m(Y) - c_m(X) >= xi_{m+1} - eta_{m+1};  and X <| Y at level m gives c_m(Y)-c_m(X) >= 0.
    So c_m(Y) - c_m(X) >= (xi_{m+1} - eta_{m+1})^+ >= min(xi_{m+1},d) - min(eta_{m+1},d),
    the last step because u |-> min(u,d) is non-decreasing and 1-Lipschitz.  QED

  LEMMA OM-DEC (PROVED).  If d >= e and Z has >= d positive entries then Om_d Z <| Om_e Z.
    Proof.  By (OM-CAP) the level-m value is c_m(Z) - min(zeta_1,d) + min(zeta_{m+1},d), and
    since zeta_1 >= zeta_{m+1} the map d |-> min(zeta_1,d) - min(zeta_{m+1},d) is
    non-decreasing.  QED

  THEOREM CAP-STEP-MONO (PROVED).  If A <| B, both HH steps are legal, and max(A) >= max(B),
  then hh(A) <| hh(B).
    Proof.  Put d := max A >= e := max B.  (CAP-TAIL) plus d >= e gives
      c_m(rest B) - c_m(rest A) = [c_m(B) - c_m(A)] + min(d,m) - min(e,m) >= 0,
    so rest A <| rest B.  Both rests have >= d resp. >= e positive entries by legality, so
      hh(A) = Om_d(rest A) <|(OM-DEC) Om_e(rest A) <|(OM-MONO) Om_e(rest B) = hh(B).  QED

  COROLLARY PLATEAU.  A >= B in dominance with equal sums and max A = max B, both steps legal
  ==> hh(A) >= hh(B) in dominance with equal sums.  (This is the statement E47 was reaching
  for; CAP-STEP-MONO is strictly stronger -- it needs neither equal sums nor equal maxima.)

  COROLLARY DOM-MAJ-IF-MAXORD.  If along the joint walk of a dominance pair one has
  max(A^(k)) >= max(B^(k)) at every k with A^(k) non-terminal, then sum(A^(k)) <= sum(B^(k))
  for every k -- i.e. (DOM-MAJ) holds for that pair.  PROVED, not measured.

  WHAT IS LEFT is exactly (MAXORD): the joint states at which A's maximum has already fallen
  BELOW B's.  Block [7] counts them.  Block [8] records four candidate repairs, all REFUTED
  by their own runs, three of them mine.

RULING CO': stepA lifted BY SOURCE TEXT from w61_r29_c1audit.py; runA/runB lifted too and
diffed on every trajectory call.  No SAT, no solver, no exhaustive search of an infeasible
space -- every sweep is a census over a stated finite population.  INTERNAL HARD LIMIT below.
Interpreter: .venv/bin/python3 (pure Python; neither sympy nor networkx).
"""
import re, sys, time
from collections import Counter
from pathlib import Path

T0 = time.time()
LIMIT = 240.0
ROOT = Path("$HOME/workspace/claudecode/automath")
SRC = ROOT / "problems/wowii/w61_r29_c1audit.py"
text = SRC.read_text()


def grab(t, name):
    m = re.search(r"^def %s\(.*?(?=\n(?:def |FAIL|# ---|print|NMAX|absorb))" % re.escape(name),
                  t, re.S | re.M)
    assert m, name
    return m.group(0)


ns = {"Counter": Counter, "sorted": sorted}
exec(compile("\n".join(grab(text, n) for n in ("stepA", "runA", "runB")), str(SRC), "exec"), ns)
stepA, runA, runB = ns["stepA"], ns["runA"], ns["runB"]

DIFFED = 0
FAIL = []
CTRL = []
PARTIAL = False


def over():
    global PARTIAL
    if time.time() - T0 > LIMIT:
        PARTIAL = True
        return True
    return False


def bad(tag, detail):
    FAIL.append("%s  %s" % (tag, detail))
    print("   ** DEFECT %s  %s" % (tag, detail))


def ctrl(name, hits, must_fire=True):
    ok = (hits > 0) if must_fire else (hits == 0)
    CTRL.append((name, hits, ok))
    print("    [%s] %-84s hits=%d" % ("ok" if ok else "DEAD", name, hits))
    if not ok:
        bad("CONTROL-DEAD", name)


def norm(x):
    return tuple(sorted([v for v in x if v > 0], reverse=True))


def step(X):
    r = stepA(list(X))
    if r == "TERMINAL":
        return ()
    if r is None:
        return None
    return norm(r)


def traj(X):
    """full HH trajectory as a list of states ending in (), or None if X aborts.
    Cross-checked against runA/runB (diffed) for the step count."""
    global DIFFED
    out = [X]
    cur = X
    for _ in range(400):
        nxt = step(cur)
        if nxt is None:
            return None
        out.append(nxt)
        if nxt == ():
            a, b = runA(list(X)), runB(list(X))
            if a != b:
                print("!! IMPLEMENTATION DISAGREEMENT on %s : %s %s" % (X, a, b))
                sys.exit(2)
            DIFFED += 1
            if a[0] is None or a[0] != len(out) - 1:
                bad("TRAJ-LEN", "%s : runA says %s steps, traj says %d" % (X, a[0], len(out) - 1))
            return out
        cur = nxt
    return None


def parts(n, mx=None):
    mx = n if mx is None else mx
    if n == 0:
        yield ()
        return
    for p in range(min(n, mx), 0, -1):
        for r in parts(n - p, p):
            yield (p,) + r


def cap(X, m):
    return sum(min(v, m) for v in X)


def MX(X):
    return X[0] if X else 0


def cle(A, B):
    """A <| B : c_m(A) <= c_m(B) for every m (c_m is constant beyond max)."""
    M = max(MX(A), MX(B))
    return all(cap(A, m) <= cap(B, m) for m in range(M + 1))


def dominates(a, b):
    n = max(len(a), len(b))
    A = list(a) + [0] * (n - len(a))
    B = list(b) + [0] * (n - len(b))
    sa = sb = 0
    for x, y in zip(A, B):
        sa += x
        sb += y
        if sb > sa:
            return False
    return True


def conj(X):
    return tuple(sum(1 for v in X if v >= t) for t in range(1, MX(X) + 1))


def Om(Z, d):
    return norm([z - 1 for z in Z[:d]] + list(Z[d:]))


def rho(X, v):
    return sum(1 for i, x in enumerate(X) if i >= 1 and x >= v)


NMAX = 16
POP = {}          # terminating partition -> trajectory
ALLP = []         # every partition of every N <= NMAX with <= 10 parts
for N in range(1, NMAX + 1):
    for p in parts(N):
        if len(p) <= 10:
            ALLP.append(p)
            t = traj(p)
            if t is not None:
                POP[p] = t
POP[()] = [()]
BYN = {}
for p in POP:
    BYN.setdefault(sum(p), []).append(p)

print("=" * 100)
print("w61 r46 -- E47 harvested (BURNED); the capped-mass dictionary, OM-MONO, OM-DEC and")
print("           Theorem CAP-STEP-MONO.  Interpreter .venv/bin/python3 (no sympy, no networkx).")
print("=" * 100)
print("population: %d partitions of N <= %d with <= 10 parts ; %d of them TERMINATE"
      % (len(ALLP), NMAX, len(POP) - 1))

# ============================================================ 0. E47's CENTRAL CLAIM, MEASURED
print("\n[0d] E47's load-bearing equivalence 'dominance <=> conjugate pointwise <=', MEASURED.")
print("     For partitions of the SAME N, conjugate pointwise <= forces EQUALITY, so the")
print("     equivalence cannot hold; and pointwise <= is CONTAINMENT, a different order.")
eq_pairs = ptwise = domn = both_ne = 0
ex0 = None
for N, lst in sorted(BYN.items()):
    for A in lst:
        for B in lst:
            if A == B or N == 0:
                continue
            eq_pairs += 1
            ca, cb = conj(A), conj(B)
            L = max(len(ca), len(cb))
            ca2 = list(ca) + [0] * (L - len(ca))
            cb2 = list(cb) + [0] * (L - len(cb))
            pw = all(x <= y for x, y in zip(ca2, cb2))
            dm = dominates(A, B)
            if pw:
                ptwise += 1
            if dm:
                domn += 1
            if dm and not pw and ex0 is None:
                ex0 = (A, B, ca, cb)
            if dm != pw:
                both_ne += 1
print("     equal-sum ordered pairs tested                 : %d" % eq_pairs)
print("     satisfying conjugate POINTWISE <=              : %d" % ptwise)
print("     satisfying DOMINANCE                           : %d" % domn)
print("     pairs where the two verdicts DISAGREE          : %d   e.g. %s" % (both_ne, ex0))
ctrl("CORRUPT CONTROL: E47's equivalence is FALSE on equal-sum pairs (disagreements exist)",
     both_ne)
ctrl("CONTROL: dominance pairs at equal sums are non-vacuous", domn)
if ptwise:
    bad("E47-PTWISE", "conjugate pointwise <= held at %d equal-sum pairs; expected 0" % ptwise)

# ==================================================== 1. THE DICTIONARY (CAP-STEP), REBUILT
print("\n[1] (CAP-STEP)  c_m(hh X) = c_m(X) - d - min(d,m) + min(rho_{m+1}(X), d).")
print("    Verified against the lifted stepA on every partition of the population whose step")
print("    is legal, at every level m from 0 to max+2.  A CORRUPT variant that drops the cap")
print("    at d must mispredict.")
cs_ok = cs_bad = cs_corrupt = 0
ex1 = None
for X in ALLP:
    nx = step(X)
    if nx is None:
        continue
    d = X[0]
    for m in range(0, d + 3):
        pred = cap(X, m) - d - min(d, m) + min(rho(X, m + 1), d)
        corr = cap(X, m) - d - min(d, m) + rho(X, m + 1)
        act = cap(nx, m)
        if pred == act:
            cs_ok += 1
        else:
            cs_bad += 1
            if ex1 is None:
                ex1 = (X, m, pred, act)
        if corr != act:
            cs_corrupt += 1
print("    instances checked : %d ; agreements : %d ; MISPREDICTIONS : %d   e.g. %s"
      % (cs_ok + cs_bad, cs_ok, cs_bad, ex1))
print("    corrupt variant (cap at d removed) mispredictions : %d" % cs_corrupt)
if cs_bad:
    bad("CAP-STEP", "%d mispredictions" % cs_bad)
ctrl("CORRUPT CONTROL: dropping the cap at d breaks (CAP-STEP)", cs_corrupt)
ctrl("CONTROL: (CAP-STEP) was tested on a non-empty population", cs_ok)

print("\n[1b] (CAP-DROP) hh(X) <| X, and (CAP-TAIL) c_m(rest X) = c_m(X) - min(d,m).")
cd_ok = cd_bad = ct_ok = ct_bad = 0
for X in ALLP:
    nx = step(X)
    if nx is None:
        continue
    if cle(nx, X):
        cd_ok += 1
    else:
        cd_bad += 1
    rst = norm(X[1:])
    for m in range(0, X[0] + 2):
        if cap(rst, m) == cap(X, m) - min(X[0], m):
            ct_ok += 1
        else:
            ct_bad += 1
print("    (CAP-DROP) : %d / %d hold ; violations %d" % (cd_ok, cd_ok + cd_bad, cd_bad))
print("    (CAP-TAIL) : %d / %d hold ; violations %d" % (ct_ok, ct_ok + ct_bad, ct_bad))
if cd_bad or ct_bad:
    bad("CAP-DROP/TAIL", "%d / %d" % (cd_bad, ct_bad))

# =========================================================== 2. <| IS THE RIGHT ORDER
print("\n[2a] At EQUAL sums, X <| Y is exactly X >= Y in dominance.  Censused on every")
print("     equal-sum ordered pair of the population.")
a_agree = a_dis = 0
ex2 = None
for N, lst in sorted(BYN.items()):
    for A in lst:
        for B in lst:
            if A == B:
                continue
            if cle(A, B) == dominates(A, B):
                a_agree += 1
            else:
                a_dis += 1
                if ex2 is None:
                    ex2 = (A, B)
print("     pairs where <| and dominance AGREE : %d ; DISAGREE : %d   e.g. %s"
      % (a_agree, a_dis, ex2))
print("     sec 90 breakdown -- the verdict could have gone either way on BOTH sides:")
print("       pairs where dominance is TRUE : %d ; where it is FALSE : %d" % (domn, eq_pairs - domn))
if a_dis:
    bad("CAP-EQ-DOM", "%d disagreements" % a_dis)

print("\n[2b] <| gives sum(X) <= sum(Y) -- the (DOM-MAJ) conclusion at k = 0 -- and it is")
print("     STRICTLY weaker than dominance once the sums may differ.")
n_cle = n_sum_ok = n_unequal = 0
for A in POP:
    for B in POP:
        if not cle(A, B):
            continue
        n_cle += 1
        if sum(A) <= sum(B):
            n_sum_ok += 1
        if sum(A) != sum(B):
            n_unequal += 1
print("     terminating pairs with A <| B : %d ; of them sum(A) <= sum(B) : %d ; unequal sums : %d"
      % (n_cle, n_sum_ok, n_unequal))
if n_sum_ok != n_cle:
    bad("CAP-SUM", "<| failed to give sum(A) <= sum(B) somewhere")
ctrl("CONTROL: <| reaches genuinely unequal-sum pairs (it is not dominance in disguise)",
     n_unequal)

print("\n[2c] <| is generated by 'delete a unit' and 'move a unit UP': both moves lower every")
print("     c_m, and the two together reach every <|-pair.  The two moves are censused here.")
mv_ok = mv_bad = 0
for X in ALLP:
    for i in range(len(X)):
        Y = norm(list(X[:i]) + [X[i] - 1] + list(X[i + 1:]))
        if cle(Y, X):
            mv_ok += 1
        else:
            mv_bad += 1
    for i in range(len(X)):
        for j in range(len(X)):
            if i == j or X[j] < X[i]:
                continue
            Z = list(X)
            Z[i] -= 1
            Z[j] += 1
            if min(Z) < 0:
                continue
            Y = norm(Z)
            if cle(Y, X):
                mv_ok += 1
            else:
                mv_bad += 1
print("     generator instances : %d ; failures : %d" % (mv_ok + mv_bad, mv_bad))
if mv_bad:
    bad("CAP-GEN", "%d generator failures" % mv_bad)
print("     CONVERSE, which is the half that makes 'generated' a claim and not a remark:")
print("     for every <|-pair A <| B with A != B there is a SINGLE such move B -> C with")
print("     A <| C <| B and C != B.  Censused (not assumed).")
gen_t = gen_bad = 0
exg = None
for B in ALLP:
    if over():
        break
    moves = set()
    for i in range(len(B)):
        moves.add(norm(list(B[:i]) + [B[i] - 1] + list(B[i + 1:])))
    for i in range(len(B)):
        for j in range(len(B)):
            if i == j or B[j] < B[i]:
                continue
            Z = list(B)
            Z[i] -= 1
            Z[j] += 1
            if min(Z) >= 0:
                moves.add(norm(Z))
    moves.discard(B)
    for A in ALLP:
        if A == B or not cle(A, B):
            continue
        gen_t += 1
        if not any(cle(A, C) for C in moves):
            gen_bad += 1
            if exg is None:
                exg = (A, B)
print("     <|-pairs with A != B : %d ; with NO single move towards A : %d   e.g. %s"
      % (gen_t, gen_bad, exg))
if gen_bad:
    bad("CAP-GEN-CONV", "%d pairs unreachable in one move" % gen_bad)
ctrl("CONTROL: the converse census is non-vacuous", gen_t)

# ========================================================= 3. LEMMA OM-MONO
print("\n[3] LEMMA OM-MONO (PROVED): X <| Y and both with >= d positive entries ==> Om_d X <| Om_d Y.")
om_t = om_bad = 0
om_dom_t = om_dom_bad = 0
om_rev = 0
ex3 = None
for X in ALLP:
    if over():
        break
    for Y in ALLP:
        if not cle(X, Y):
            continue
        for d in range(1, min(len(X), len(Y)) + 1):
            om_t += 1
            if not cle(Om(X, d), Om(Y, d)):
                om_bad += 1
                if ex3 is None:
                    ex3 = (X, Y, d)
            if cle(Om(Y, d), Om(X, d)):
                om_rev += 1
for N, lst in sorted(BYN.items()):
    for X in lst:
        for Y in lst:
            if X == Y or not dominates(X, Y):
                continue
            for d in range(1, min(len(X), len(Y)) + 1):
                om_dom_t += 1
                if not dominates(Om(X, d), Om(Y, d)):
                    om_dom_bad += 1
print("    <|-form   : instances %d ; failures %d   e.g. %s" % (om_t, om_bad, ex3))
print("    dominance-form (equal sums) : instances %d ; failures %d" % (om_dom_t, om_dom_bad))
print("    instances where the REVERSE also holds (so the census is not trivially two-sided) : %d"
      % om_rev)
if om_bad or om_dom_bad:
    bad("OM-MONO", "%d / %d" % (om_bad, om_dom_bad))
ctrl("CONTROL: OM-MONO was tested on a non-empty population", om_t)
print("    MY OWN LABELLING DEFECT, DISCLOSED.  I first wrote the next block as a CORRUPT")
print("    control -- 'mixing two different d's must fail'.  It must NOT: Om_d X <| Om_e Y for")
print("    d >= e is exactly OM-DEC followed by OM-MONO, so a failure here would refute one of")
print("    the two lemmas.  It is re-labelled a COROLLARY CHECK and must come back SILENT.")
mix_t = mix_bad = 0
for X in ALLP:
    if over():
        break
    for Y in ALLP:
        if not cle(X, Y):
            continue
        for d in range(2, min(len(X), len(Y)) + 1):
            mix_t += 1
            if not cle(Om(X, d), Om(Y, d - 1)):
                mix_bad += 1
print("      COROLLARY CHECK  Om_d X <| Om_{d-1} Y : instances %d ; failures %d" % (mix_t, mix_bad))
ctrl("COROLLARY CHECK (OM-DEC then OM-MONO): silent, as the two lemmas require", mix_bad,
     must_fire=False)

# ========================================================= 4. LEMMA OM-DEC
print("\n[4] LEMMA OM-DEC (PROVED): d >= e and Z with >= d positive entries ==> Om_d Z <| Om_e Z.")
dec_t = dec_bad = dec_rev = 0
ex4 = None
for Z in ALLP:
    for d in range(1, len(Z) + 1):
        for e in range(1, d + 1):
            dec_t += 1
            if not cle(Om(Z, d), Om(Z, e)):
                dec_bad += 1
                if ex4 is None:
                    ex4 = (Z, d, e)
            if d > e and cle(Om(Z, e), Om(Z, d)):
                dec_rev += 1
print("    instances %d ; failures %d   e.g. %s" % (dec_t, dec_bad, ex4))
print("    instances with d > e where the REVERSE also holds : %d" % dec_rev)
if dec_bad:
    bad("OM-DEC", "%d failures" % dec_bad)
ctrl("CONTROL: OM-DEC has strict instances (the reverse does not always hold)",
     dec_t - dec_rev)

# ================================================ 5. THEOREM CAP-STEP-MONO
print("\n[5] THEOREM CAP-STEP-MONO (PROVED): A <| B, both steps legal, max A >= max B")
print("    ==> hh A <| hh B.  Censused over EVERY <|-pair of the population, terminating or")
print("    not, with both steps legal.")
th_t = th_bad = 0
th_eq = th_gt = 0
th_drop_t = th_drop_bad = 0
ex5 = None
ex5b = None
for A in ALLP:
    if over():
        break
    sA = step(A)
    if sA is None:
        continue
    for B in ALLP:
        if not cle(A, B):
            continue
        sB = step(B)
        if sB is None:
            continue
        if MX(A) >= MX(B):
            th_t += 1
            if MX(A) == MX(B):
                th_eq += 1
            else:
                th_gt += 1
            if not cle(sA, sB):
                th_bad += 1
                if ex5 is None:
                    ex5 = (A, B, sA, sB)
        else:
            th_drop_t += 1
            if not cle(sA, sB):
                th_drop_bad += 1
                if ex5b is None:
                    ex5b = (A, B, sA, sB)
print("    with max A >= max B : instances %d ; FAILURES %d   e.g. %s" % (th_t, th_bad, ex5))
print("    sec 90 split of those instances: max A = max B : %d  (OM-DEC idle, OM-MONO alone)" % th_eq)
print("                                     max A > max B : %d  (OM-DEC doing real work)" % th_gt)
print("    CORRUPT CONTROL, the same statement with max A < max B :")
print("      instances %d ; failures %d   e.g. %s" % (th_drop_t, th_drop_bad, ex5b))
if th_bad:
    bad("CAP-STEP-MONO", "%d failures" % th_bad)
ctrl("CONTROL: the theorem's hypothesis is satisfiable (non-empty census)", th_t)
ctrl("CORRUPT CONTROL: dropping 'max A >= max B' BREAKS the theorem -- so that hypothesis is"
     " doing real work", th_drop_bad)

print("\n[5b] COROLLARY PLATEAU: dominance + equal sums + equal maxima ==> dominance of the")
print("     successors.  This is the statement E47's trace was reaching for.")
pl_t = pl_bad = 0
pl_gap_t = pl_gap_dom = 0
for N, lst in sorted(BYN.items()):
    for A in lst:
        for B in lst:
            if A == B or not dominates(A, B):
                continue
            sA, sB = step(A), step(B)
            if sA is None or sB is None:
                continue
            if MX(A) == MX(B):
                pl_t += 1
                if not dominates(sA, sB):
                    pl_bad += 1
            else:
                pl_gap_t += 1
                if dominates(sA, sB):
                    pl_gap_dom += 1
print("     equal-maxima dominance pairs : %d ; successors NOT in dominance : %d"
      % (pl_t, pl_bad))
print("     unequal-maxima dominance pairs : %d ; of those, successors still in dominance : %d"
      % (pl_gap_t, pl_gap_dom))
if pl_bad:
    bad("PLATEAU", "%d failures" % pl_bad)
ctrl("CONTROL: unequal-maxima dominance pairs exist, and their successors leave dominance"
     " (the maxima hypothesis is not vacuous)", pl_gap_t - pl_gap_dom)

print("\n[5c] THE SHARPEST FORM OF THE ROUND'S POINT.  Over equal-sum DOMINANCE pairs whose")
print("     steps are both legal: how often does the step DESTROY dominance, and in how many")
print("     of those very instances does <| survive?  This is why the coordinates matter.")
d_lost = d_lost_cap_lost = d_kept = 0
for N, lst in sorted(BYN.items()):
    if over():
        break
    for A in lst:
        sA = step(A)
        if sA is None:
            continue
        for B in lst:
            if A == B or not dominates(A, B):
                continue
            sB = step(B)
            if sB is None:
                continue
            if dominates(sA, sB):
                d_kept += 1
            else:
                d_lost += 1
                if not cle(sA, sB):
                    d_lost_cap_lost += 1
print("     dominance SURVIVES the step : %d" % d_kept)
print("     dominance is DESTROYED      : %d" % d_lost)
print("     of those, <| ALSO destroyed  : %d" % d_lost_cap_lost)
if d_lost_cap_lost:
    bad("CAP-SURVIVES", "<| died at %d of the instances where dominance died" % d_lost_cap_lost)
ctrl("CONTROL: dominance really is destroyed by the step -- so the 0 above is a statement",
     d_lost)

print("\n[5d] THREE CLAIMS FROM E47's TRACE, ADJUDICATED AGAINST THIS STEP.")
print("     (i)  its counterexample to step-monotonicity, A=(4,2,2,2) vs B=(3,3,2,2):")
print("          step((4,2,2,2)) = %s   -- the rest has %d entries and the pivot is %d, so the"
      % (step((4, 2, 2, 2)), 3, 4))
print("          step ABORTS and the pair cannot witness anything.  E47 wrote 'd = 4 = len(rest)'.")
print("     (ii) its own refutation of its C_m family, A=(3,3,2,1,1) vs B=(2,2,2,2,2):")
tA, tB = POP.get((3, 3, 2, 1, 1)), POP.get((2, 2, 2, 2, 2))
if tA and tB:
    for k in range(3):
        a, b = tA[min(k, len(tA) - 1)], tB[min(k, len(tB) - 1)]
        print("          k=%d  a=%s b=%s  g=%d  2*(prefix_m B - prefix_m A) for m=1,2,3 = %s"
              "  dominance=%s  <|=%s"
              % (k, a, b, sum(b) - sum(a),
                 [2 * (sum(b[:m]) - sum(a[:m])) for m in (1, 2, 3)],
                 dominates(a, b), cle(a, b)))
    print("          CONFIRMED: at k=2 the gap is %d and the m=2 demand is %d, so C_m dies on a"
          % (sum(tB[2]) - sum(tA[2]), 2 * (sum(tB[2][:2]) - sum(tA[2][:2]))))
    print("          REACHABLE pair -- while <| holds at every k.  E47's own refutation stands.")
else:
    bad("E47-CM", "the pair is not in the terminating population")
print("     (iii) its claim that (3,2,2,1) is graphic but ABORTS under this step:")
print("          trajectory = %s ; runA = %s ; runB = %s  -- it TERMINATES; the claim is FALSE"
      % (POP.get((3, 2, 2, 1)), runA([3, 2, 2, 1]), runB([3, 2, 2, 1])))
if (3, 2, 2, 1) not in POP:
    bad("E47-ABORT", "(3,2,2,1) really does abort -- E47 was right and this line is wrong")

# ============================================ 6. THE WALK: WHAT THE THEOREM COVERS
print("\n[6] THE JOINT WALK from every equal-sum dominance pair of TERMINATING partitions of")
print("    N <= %d with <= 10 parts.  Three things are counted: whether <| survives; how many" % NMAX)
print("    joint states have A's maximum already BELOW B's (the residue the theorem does not")
print("    reach); and how many PAIRS are covered end-to-end, hence PROVED by the corollary.")
w_pairs = w_states = w_capbad = 0
w_nonterm = w_maxbad = 0
w_covered = 0
exw = None
exm = None
for N, lst in sorted(BYN.items()):
    if over():
        break
    for A in lst:
        for B in lst:
            if A == B or not dominates(A, B):
                continue
            w_pairs += 1
            a, b = A, B
            k = 0
            covered = True
            while k < 60:
                w_states += 1
                if not cle(a, b):
                    w_capbad += 1
                    if exw is None:
                        exw = (A, B, k, a, b)
                    break
                if a != ():
                    w_nonterm += 1
                    if MX(a) < MX(b):
                        w_maxbad += 1
                        covered = False
                        if exm is None:
                            exm = (A, B, k, a, b)
                na, nb = step(a), step(b)
                if na is None or nb is None or na == () or nb == ():
                    break
                a, b, k = na, nb, k + 1
            if covered:
                w_covered += 1
print("    dominance pairs walked                          : %d" % w_pairs)
print("    joint states visited                            : %d" % w_states)
print("    <| VIOLATIONS along the trajectories            : %d   e.g. %s" % (w_capbad, exw))
print("    joint states with A non-terminal                : %d   (equals the line above BY" % w_nonterm)
print("      CONSTRUCTION -- the walk stops before pushing a terminal state, so this is not an")
print("      independent measurement and is printed only to make that explicit)" % ())
print("    of those, states with max(A) < max(B)  [RESIDUE]: %d   e.g. %s" % (w_maxbad, exm))
print("    PAIRS covered end-to-end by CAP-STEP-MONO       : %d of %d  -- (DOM-MAJ) PROVED"
      % (w_covered, w_pairs))
print("    PAIRS left to the residue                       : %d" % (w_pairs - w_covered))
if w_capbad:
    bad("WALK-CAP", "%d <| violations on reachable states" % w_capbad)
ctrl("CONTROL: the walk visited states (non-vacuous)", w_states)
ctrl("CORRUPT CONTROL: max(A) >= max(B) DOES fail along these very trajectories, so the"
     " end-to-end coverage count is not an artefact", w_maxbad)

# ========================================== 7. FOUR CANDIDATE REPAIRS, ALL REFUTED
print("\n[7] FOUR CANDIDATE REPAIRS FOR THE RESIDUE.  Three are mine, one is E47's.  ALL FOUR")
print("    ARE REFUTED BY THIS RUN.  Each is reported with the population it died on.")
TPOP = [p for p in POP]


def closure_count(pred, name):
    t = v = 0
    ex = None
    for A in TPOP:
        if over():
            break
        if A == ():
            continue
        sA = step(A)
        for B in TPOP:
            if not pred(A, B):
                continue
            sB = step(B)
            if sA is None or sB is None:
                continue
            t += 1
            if not pred(sA, sB):
                v += 1
                if ex is None:
                    ex = (A, B, sA, sB)
    print("    %-22s pairs %6d ; CLOSURE VIOLATIONS %5d   e.g. %s" % (name, t, v, ex))
    return t, v


def C2(A, B):
    return (sum(B) - sum(A)) >= 2 * (MX(B) - MX(A))


def C3(A, B):
    """E47's proposed third condition: b1 - a1 <= g/2 + (a0 - b0)."""
    a1 = A[1] if len(A) > 1 else 0
    b1 = B[1] if len(B) > 1 else 0
    return 2 * (b1 - a1) <= (sum(B) - sum(A)) + 2 * (MX(A) - MX(B))


t1, v1 = closure_count(lambda a, b: cle(a, b), "<| alone")
t2, v2 = closure_count(lambda a, b: cle(a, b) and C2(a, b), "<| and (C2)")
t3, v3 = closure_count(lambda a, b: cle(a, b) and C2(a, b) and C3(a, b), "<|,(C2),E47's (C3)")


def phase(A, B):
    for S in POP[B]:
        if MX(S) <= MX(A):
            return S
    return None


def PH(A, B):
    S = phase(A, B)
    return S is not None and cle(A, S)


t4, v4 = closure_count(PH, "phase-shifted <| (mine)")
for nm, tt, vv in (("<|", t1, v1), ("<|+C2", t2, v2), ("<|+C2+C3", t3, v3), ("phase", t4, v4)):
    if vv == 0:
        bad("REPAIR-SURVIVED", "%s showed NO closure violation -- re-examine" % nm)
ctrl("CORRUPT CONTROL: every one of the four candidate repairs is REFUTED by its own run",
     min(v1, v2, v3, v4))

print("\n[7b] TWO FURTHER STATEMENTS OF MINE, BOTH REFUTED, both on TERMINATING pairs.")
print("     (DM-CAP-MAX)  A <| B and max A >= max B AT THE START ==> sum(A^(k)) <= sum(B^(k)).")
dm_t = dm_v = 0
exdm = None


def sk(tr, k):
    return sum(tr[min(k, len(tr) - 1)])


for A in POP:
    if over():
        break
    for B in POP:
        if MX(A) < MX(B) or not cle(A, B):
            continue
        dm_t += 1
        K = max(len(POP[A]), len(POP[B]))
        if any(sk(POP[A], k) > sk(POP[B], k) for k in range(K)):
            dm_v += 1
            if exdm is None:
                exdm = (A, B)
print("     pairs %d ; VIOLATIONS %d   smallest-seen %s" % (dm_t, dm_v, exdm))
print("     (TRUNC)  capping B at a level e sheds no faster than B itself.")
tr_t = tr_v = 0
extr = None
for B in POP:
    for e in range(1, MX(B)):
        T = norm([min(v, e) for v in B])
        if T not in POP:
            continue
        tr_t += 1
        K = max(len(POP[T]), len(POP[B]))
        if any(sk(POP[T], k) > sk(POP[B], k) for k in range(K)):
            tr_v += 1
            if extr is None:
                extr = (B, e, T)
print("     instances %d ; VIOLATIONS %d   e.g. %s" % (tr_t, tr_v, extr))
ctrl("CORRUPT CONTROL: (DM-CAP-MAX) is refuted by its own run", dm_v)
ctrl("CORRUPT CONTROL: (TRUNC) is refuted by its own run", tr_v)

print("\n[7c] (DOM-MAJ) itself, re-censused in these coordinates as a standing check.")
dj_t = dj_v = 0
for N, lst in sorted(BYN.items()):
    if over():
        break
    for A in lst:
        for B in lst:
            if A == B or not dominates(A, B):
                continue
            dj_t += 1
            K = max(len(POP[A]), len(POP[B]))
            if any(sk(POP[A], k) > sk(POP[B], k) for k in range(K)):
                dj_v += 1
print("     equal-sum dominance pairs of terminating partitions : %d ; violations : %d"
      % (dj_t, dj_v))
if dj_v:
    bad("DOM-MAJ", "%d violations -- this would REFUTE the conjecture" % dj_v)
ctrl("CONTROL: (DOM-MAJ) census non-vacuous", dj_t)

# ================================================================= 8. GATE
print("\n" + "=" * 100)
el = time.time() - T0
print("ELAPSED %.2f s / %.0f s internal limit ; PARTIAL=%s ; diffed runA/runB calls %d"
      % (el, LIMIT, PARTIAL, DIFFED))
good = sum(1 for _, _, ok in CTRL if ok)
print("CONTROLS %d/%d firing ; DEFECTS %d" % (good, len(CTRL), len(FAIL)))
for f in FAIL:
    print("   DEFECT: %s" % f)
print("EXIT=%d   (this is the script's own FLAG line, not the process exit code, which is 0)"
      % (1 if (FAIL or PARTIAL) else 0))
sys.exit(0)
