#!/usr/bin/env python3
"""
owner-w61 round 17 -- INDEPENDENT RECOMPUTATION of the Theorem GFANnu enumeration
roster for the whole folded range 1 <= nu <= 10.

Planner ruling RW61-1 (orchestration/planner_msgs/cert_cycle_2040.md): roster
completeness is a COMPUTATION, not a judging question; it is discharged by an
independent implementation written from the specification by a different author,
NOT from problems/wowii/w61_S3_GFAN_sol_check.py (which was not read while this
file was written), and then diffed against that roster both directions.

SPECIFICATION SOURCE -- notes/proofs/wowii61_draft.md only:
  * SS7.22 (c-1), the five conventions, verbatim reading:
      - the list at the start of step p+1 is
          C-part: L+1 entries, the c-th equal to L + e_c, e_c >= 0, sum e_c = E
          A'-part: a partition lambda of 2nu - E
          plus zero entries
      - (1) unlabelled: e is a partition of E into at most L+1 non-negative
            parts, lambda is a partition of 2nu - E; distinct labellings of the
            same multiset are the same row
      - (2) zero entries are inert  -> they are simply not written down here
      - (3) no graphicality filter (superset argument)
      - (4) "clears in exactly L steps" = iterating head-deletes-the-d-largest
            reaches all-zeros in exactly L deletions; a run that would drive a
            zero entry negative, or whose head exceeds the number of remaining
            entries, is NOT A STEP SEQUENCE and is not a survivor
      - (5) L >= nu+1 (the theorem's own hypothesis); E >= 1 => L <= 2nu - E
            (Lemma FAN-8'), forcing E <= nu-1; the E = 0 rows split at lambda_1
            into the TAIL range L >= lambda_1 and the boundary rows
            nu+1 <= L < lambda_1 <= 2nu
  * SS7.13 D, Lemma TAIL: for E = 0, lambda non-empty, L >= lambda_1, the number
    of further steps is (L - lambda_1) + s0(lambda) with
    s0(lambda) := steps([lambda_1]^{lambda_1+1} u lambda); so inside that range
    "clears in exactly L" <=> s0(lambda) = lambda_1
  * SS7.12, Lemma FAN-6' + Repair Z1 + Repair AB6: a residue is KILLED iff it has
    a UNIQUE maximum w with second-largest entry <= w-2, where a residue with a
    single positive part is read as having second-largest 0 (so [w] is killed for
    w >= 2 and [1] is not).
  * SS7.22 (c-4): S(nu) = sum_{E=1}^{nu-1} (nu-E) p(E) p(2nu-E).

DELIBERATELY DIFFERENT IMPLEMENTATION (not a transliteration):
  * the Havel-Hakimi step is done on a HISTOGRAM (value -> multiplicity) of the
    positive entries, not on a sorted list; the block is consumed by walking
    values downward.  Zeros are never materialised at all.
  * a second, independent sorted-list implementation is carried alongside and
    EVERY shape is evaluated by BOTH; any disagreement is a hard failure.
  * partitions are generated by my own descending-part recursion; p(n) is
    computed independently by Euler's pentagonal recurrence and the two are
    cross-checked.
  * Lemma TAIL's formula is re-derived against direct simulation at full nu<=10
    scope as a control.

Hard self-limit inside the script (RED LINE): TIME_LIMIT_S below.  No SAT, no
graph search: this is bounded table verification over an explicitly counted
finite set (79 118 shapes total).

ONE PRODUCT: the report written to w61_r17_roster_recompute.out.
"""

import sys
import time

NU_MAX = 10
TIME_LIMIT_S = 900.0
OUT = "problems/wowii/w61_r17_roster_recompute.out"

T0 = time.time()


def tick(where):
    if time.time() - T0 > TIME_LIMIT_S:
        raise SystemExit("HARD TIME LIMIT %.0fs exceeded at %s" % (TIME_LIMIT_S, where))


# --------------------------------------------------------------------------
# (A) Havel-Hakimi step count -- implementation #1, HISTOGRAM based.
#     state: dict {positive value -> multiplicity}.  Zero entries are inert
#     (convention 2) and are therefore never stored.
#     Returns the number of deletions to reach all-zeros, or None for
#     "not a step sequence".
# --------------------------------------------------------------------------
def steps_hist(values):
    hist = {}
    for v in values:
        if v > 0:
            hist[v] = hist.get(v, 0) + 1
    npos = sum(hist.values())
    n = 0
    while npos:
        d = max(hist)
        # delete the head
        hist[d] -= 1
        if hist[d] == 0:
            del hist[d]
        npos -= 1
        # the block is the d largest NON-HEAD entries.  A zero in the block
        # would be driven negative -> not a step sequence.  (This also covers
        # "head exceeds the number of remaining entries".)
        if npos < d:
            return None
        need = d
        # Walk values downward, moving whole runs from v to v-1.  The moved
        # entries go to a PENDING dict and are merged only after the walk:
        # writing them straight back into `hist` would let a value that has
        # just been decremented be picked up again lower down the same walk.
        pending = {}
        for v in sorted(hist, reverse=True):
            if need == 0:
                break
            k = hist[v]
            if k > need:
                k = need
            hist[v] -= k
            if hist[v] == 0:
                del hist[v]
            if v - 1 > 0:
                pending[v - 1] = pending.get(v - 1, 0) + k
            else:
                npos -= k          # entries that hit 0 leave the positive pool
            need -= k
        for v, k in pending.items():
            hist[v] = hist.get(v, 0) + k
        n += 1
    return n


# --------------------------------------------------------------------------
# (B) Havel-Hakimi step count -- implementation #2, SORTED LIST based.
#     Written separately, on purpose, as an internal control on (A).
# --------------------------------------------------------------------------
def steps_list(values):
    cur = sorted([v for v in values if v > 0], reverse=True)
    n = 0
    while cur:
        d = cur[0]
        rest = cur[1:]
        if len(rest) < d:
            return None
        blk = [x - 1 for x in rest[:d]]
        if any(x < 0 for x in blk):
            return None
        cur = sorted([x for x in blk + rest[d:] if x > 0], reverse=True)
        n += 1
    return n


def steps(values):
    """Both implementations, agreement enforced."""
    a = steps_hist(values)
    b = steps_list(values)
    if a != b:
        raise SystemExit("IMPLEMENTATION DISAGREEMENT on %r: %r vs %r" % (values, a, b))
    return a


# --------------------------------------------------------------------------
# (C) Partitions -- own descending-part recursion; p(n) independently by Euler.
# --------------------------------------------------------------------------
def partitions(n, cap=None):
    """All partitions of n as descending tuples, parts <= cap."""
    if cap is None:
        cap = n
    if n == 0:
        yield ()
        return
    top = min(n, cap)
    for first in range(top, 0, -1):
        for tail in partitions(n - first, first):
            yield (first,) + tail


def p_euler(n, _memo={0: 1}):
    """Euler pentagonal-number recurrence -- independent of the generator."""
    if n in _memo:
        return _memo[n]
    if n < 0:
        return 0
    tot = 0
    k = 1
    while True:
        g1 = k * (3 * k - 1) // 2
        g2 = k * (3 * k + 1) // 2
        if g1 > n and g2 > n:
            break
        sgn = -1 if k % 2 == 0 else 1
        if g1 <= n:
            tot += sgn * p_euler(n - g1)
        if g2 <= n:
            tot += sgn * p_euler(n - g2)
        k += 1
    _memo[n] = tot
    return tot


# --------------------------------------------------------------------------
# (D) Lemma FAN-6' kill test (Repair Z1 / AB6 convention).
# --------------------------------------------------------------------------
def fan6_cert(lam):
    """(w, second-largest) with the single-positive-part convention 2nd = 0."""
    s = sorted(lam, reverse=True)
    w = s[0] if s else 0
    second = s[1] if len(s) > 1 else 0
    return (w, second)


def fan6_kills(lam):
    w, second = fan6_cert(lam)
    return w > second and second <= w - 2


def fmt_part(lam):
    return "+".join(str(x) for x in lam) if lam else "()"


# --------------------------------------------------------------------------
# (E) The three branches, per nu.
# --------------------------------------------------------------------------
def s0(lam):
    lam1 = lam[0]
    return steps([lam1] * (lam1 + 1) + list(lam))


def run_nu(nu, rep):
    tick("nu=%d" % nu)
    two = 2 * nu
    parts = list(partitions(two))
    if len(parts) != p_euler(two):
        raise SystemExit("partition generator disagrees with p(%d)" % two)

    # ---- branch 1: E = 0, TAIL range L >= lambda_1 -------------------------
    tail_col = []
    tail_surv = []
    for lam in parts:
        v = s0(lam)
        if v is None:
            raise SystemExit("s0 aborted on %r" % (lam,))
        tail_col.append((lam, v))
        if v == lam[0]:
            tail_surv.append(lam)

    # ---- branch 2: E = 0 boundary rows nu+1 <= L < lambda_1 ----------------
    bd_pairs = 0
    bd_surv = []
    for lam in parts:
        for L in range(nu + 1, lam[0]):
            bd_pairs += 1
            lst = [L] * (L + 1) + list(lam)
            n = steps(lst)
            if n == L:
                bd_surv.append((L, lam))

    # ---- branch 3: E >= 1 rows --------------------------------------------
    e1_tested = 0
    e1_surv = []
    per_E = {}
    for E in range(1, nu):
        eparts = list(partitions(E))
        if len(eparts) != p_euler(E):
            raise SystemExit("partition generator disagrees with p(%d)" % E)
        lparts = list(partitions(two - E))
        cnt = 0
        for L in range(nu + 1, two - E + 1):
            for e in eparts:
                if len(e) > L + 1:          # convention 1; never fires since L+1 > E
                    continue
                cpart = [L + x for x in e] + [L] * (L + 1 - len(e))
                for lam in lparts:
                    cnt += 1
                    n = steps(cpart + list(lam))
                    if n == L:
                        e1_surv.append((L, E, e, lam))
            tick("nu=%d E=%d L=%d" % (nu, E, L))
        per_E[E] = cnt
        e1_tested += cnt

    # closed form S(nu), evaluated independently of the loop
    S_closed = sum((nu - E) * p_euler(E) * p_euler(two - E) for E in range(1, nu))
    per_E_closed = {E: (nu - E) * p_euler(E) * p_euler(two - E) for E in range(1, nu)}

    misses = [x for x in bd_surv if not fan6_kills(x[1])]
    misses += [x for x in e1_surv if not fan6_kills(x[3])]
    tail_misses = [lam for lam in tail_surv if not fan6_kills(lam)]

    # ---- report -----------------------------------------------------------
    rep(" ")
    rep("=" * 74)
    rep("nu = %d      (2nu = %d, p(2nu) = %d)" % (nu, two, len(parts)))
    rep("=" * 74)
    rep("  [E=0, TAIL range L >= lambda_1]  criterion s0(lambda) = lambda_1")
    rep("    partitions of %d scanned : %d" % (two, len(parts)))
    rep("    survivors               : %s"
        % (", ".join("[%s]" % fmt_part(l) for l in tail_surv) or "none"))
    rep("    FAN-6' misses           : %d" % len(tail_misses))
    rep("    s0 column               :")
    line = []
    for lam, v in tail_col:
        mark = "**" if v == lam[0] else ""
        line.append("%s%s:%d%s" % (mark, fmt_part(lam), v, mark))
    rep("      " + " . ".join(line))
    rep("  [E=0, boundary rows nu+1 <= L < lambda_1]")
    rep("    (L,lambda) pairs checked : %d" % bd_pairs)
    rep("    survivors (%d)           : %s"
        % (len(bd_surv),
           ", ".join("(%d,[%s]) cert(%d,%d)" % (L, fmt_part(l), *fan6_cert(l))
                     for L, l in bd_surv) or "none"))
    rep("  [E>=1 rows]  nu+1 <= L <= 2nu-E, e |- E, lambda |- 2nu-E")
    rep("    shapes tested (loop)     : %d" % e1_tested)
    rep("    shapes tested (closed)   : %d   %s"
        % (S_closed, "AGREE" if S_closed == e1_tested else "*** DISAGREE ***"))
    rep("    per-E (loop)             : %s" % per_E)
    rep("    per-E (closed form)      : %s" % per_E_closed)
    rep("    survivors                : %d" % len(e1_surv))
    for L, E, e, lam in e1_surv:
        rep("      L%-3d E%d e=%-12s lambda=%-16s cert(%d,%d)"
            % (L, E, fmt_part(e), fmt_part(lam), *fan6_cert(lam)))
    rep("  [Lemma FAN-6' misses over ALL survivors] : %d  -> %s"
        % (len(misses) + len(tail_misses),
           "ELIMINATED" if not (misses or tail_misses) else "*** MISS ***"))
    return {
        "nu": nu,
        "tail_surv": tail_surv,
        "bd_pairs": bd_pairs,
        "bd_surv": bd_surv,
        "e1_tested": e1_tested,
        "S_closed": S_closed,
        "e1_surv": e1_surv,
        "misses": len(misses) + len(tail_misses),
    }


# --------------------------------------------------------------------------
# (F) Control: Lemma TAIL's formula vs direct simulation, full nu<=10 scope.
# --------------------------------------------------------------------------
def tail_control(rep):
    pairs = 0
    bad = 0
    for nu in range(1, NU_MAX + 1):
        for lam in partitions(2 * nu):
            base = s0(lam)
            for L in range(lam[0], 2 * nu + 1):
                pairs += 1
                direct = steps([L] * (L + 1) + list(lam))
                if direct != (L - lam[0]) + base:
                    bad += 1
        tick("tail control nu=%d" % nu)
    rep(" ")
    rep("CONTROL -- Lemma TAIL formula (L - lambda_1) + s0(lambda) vs direct simulation")
    rep("  (lambda, L) pairs with L >= lambda_1, nu <= %d : %d" % (NU_MAX, pairs))
    rep("  mismatches                                     : %d" % bad)
    return bad


def main():
    lines = []

    def rep(s):
        lines.append(s)

    rep("=== owner-w61 round 17 -- INDEPENDENT RECOMPUTATION of the Theorem GFANnu")
    rep("=== enumeration roster, 1 <= nu <= %d  (planner ruling RW61-1(b))" % NU_MAX)
    rep("")
    rep("Written from notes/proofs/wowii61_draft.md SS7.22 (c-1)/(c-4), SS7.13 D")
    rep("(Lemma TAIL) and SS7.12 (Lemma FAN-6', Repairs Z1/AB6) ONLY.")
    rep("problems/wowii/w61_S3_GFAN_sol_check.py was NOT read while writing this.")
    rep("Two independent step-count implementations (histogram / sorted list) are")
    rep("run on EVERY shape and must agree, or the script dies.")

    results = []
    for nu in range(1, NU_MAX + 1):
        results.append(run_nu(nu, rep))

    bad = tail_control(rep)

    rep("")
    rep("=" * 74)
    rep("SUMMARY TABLE")
    rep("=" * 74)
    rep("  nu | E=0 surv | bd pairs | bd surv | E>=1 tested | E>=1 surv | FAN-6' | verdict")
    for r in results:
        rep("  %2d | %-8s | %8d | %7d | %11d | %9d | %6d | %s"
            % (r["nu"],
               ",".join("[%s]" % fmt_part(l) for l in r["tail_surv"]) or "none",
               r["bd_pairs"], len(r["bd_surv"]), r["e1_tested"], len(r["e1_surv"]),
               r["misses"],
               "ELIMINATED" if r["misses"] == 0 else "*** MISS ***"))

    tot_e1_16 = sum(r["e1_tested"] for r in results if r["nu"] <= 6)
    surv_16 = sum(len(r["e1_surv"]) for r in results if r["nu"] <= 6)
    tot_e1_710 = sum(r["e1_tested"] for r in results if r["nu"] >= 7)
    surv_710 = sum(len(r["e1_surv"]) for r in results if r["nu"] >= 7)
    rep("")
    rep("  E>=1 shapes, nu <= 6      : %d   survivors %d" % (tot_e1_16, surv_16))
    rep("  E>=1 shapes, nu = 7..10   : %d   survivors %d" % (tot_e1_710, surv_710))
    rep("  boundary pairs, nu <= 10  : %d   survivors %d"
        % (sum(r["bd_pairs"] for r in results),
           sum(len(r["bd_surv"]) for r in results)))
    rep("  TAIL-formula mismatches   : %d" % bad)
    rep("")
    fail = bad + sum(r["misses"] for r in results)
    for r in results:
        if r["S_closed"] != r["e1_tested"]:
            fail += 1
    rep("FAILURE_COUNT = %d" % fail)
    rep("elapsed %.1fs (hard limit %.0fs)" % (time.time() - T0, TIME_LIMIT_S))

    with open(OUT, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print("wrote %s  (FAILURE_COUNT=%d, %.1fs)" % (OUT, fail, time.time() - T0))


if __name__ == "__main__":
    sys.setrecursionlimit(10000)
    main()
