// Exhaustive / enriched search for counterexamples to WOWII Graffiti.pc Conjecture 133.
//
//   path(G) >= rad(G) + floor(l(G))^{cC4(G)},   cC4 = 1 iff G has no 4-cycle (subgraph)
//
//   path(G) = #vertices of a largest induced path
//   rad(G)  = min eccentricity
//   l(G)    = (1/n) * sum_v alpha(G[N(v)])
//
// Generation: connected graphs are generated by adding one vertex at a time
// (valid because every connected graph on k+1>=2 vertices has a non-cut vertex,
//  whose deletion leaves a connected graph on k vertices).
// Isomorph-rejection by canonical certificate (WL-refined colours + branch&bound
// minimal adjacency certificate) at every level except the last, where we simply
// test all candidates (duplicates are harmless for a falsification search).
//
// usage: ./enum133 MAXN C4FREE_ONLY
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>

typedef unsigned __int128 u128;
#define MAXV 16

static inline int pc(int x) { return __builtin_popcount(x); }

/* ------------------------------------------------------------------ */
/* invariants                                                          */
/* ------------------------------------------------------------------ */

static int connectedG(int *adj, int n) {
  int seen = 1, fr = 1;
  while (fr) {
    int nf = 0;
    for (int v = 0; v < n; v++) if (fr >> v & 1) nf |= adj[v];
    nf &= ~seen; seen |= nf; fr = nf;
  }
  return seen == (1 << n) - 1;
}

/* 4-cycle as a subgraph  <=>  two distinct vertices with >=2 common neighbours */
static int hasC4(int *adj, int n) {
  for (int u = 0; u < n; u++)
    for (int v = u + 1; v < n; v++)
      if (pc(adj[u] & adj[v]) >= 2) return 1;
  return 0;
}

static int radiusG(int *adj, int n) {
  int best = 1000;
  for (int s = 0; s < n; s++) {
    int seen = 1 << s, fr = 1 << s, d = 0;
    while (1) {
      int nf = 0;
      for (int v = 0; v < n; v++) if (fr >> v & 1) nf |= adj[v];
      nf &= ~seen;
      if (!nf) break;
      seen |= nf; fr = nf; d++;
    }
    if (d < best) best = d;
  }
  return best;
}

static int NG;
static int alpha_rec(int *adj, int mask) {
  if (!mask) return 0;
  int v = -1, bd = -1;
  for (int u = 0; u < NG; u++)
    if (mask >> u & 1) { int dg = pc(adj[u] & mask); if (dg > bd) { bd = dg; v = u; } }
  if (bd == 0) return pc(mask);
  int a = alpha_rec(adj, mask & ~(1 << v));
  int b = 1 + alpha_rec(adj, mask & ~((1 << v) | adj[v]));
  return a > b ? a : b;
}

static int bestpath;
static void dfsp(int *adj, int last, int pmask, int forbid, int len, int full) {
  if (len > bestpath) bestpath = len;
  int avail = full & ~pmask & ~forbid;
  if (len + pc(avail) <= bestpath) return;
  int cands = adj[last] & avail;
  int nf = forbid | adj[last];
  while (cands) {
    int w = cands & -cands; cands ^= w;
    dfsp(adj, __builtin_ctz(w), pmask | w, nf, len + 1, full);
  }
}
static int pathnum(int *adj, int n) {
  bestpath = 0;
  int full = (1 << n) - 1;
  for (int s = 0; s < n; s++) dfsp(adj, s, 1 << s, 0, 1, full);
  return bestpath;
}

/* early-exit variant: is there an induced path on >= target vertices? */
static int target_hit;
static void dfsp2(int *adj, int last, int pmask, int forbid, int len, int full, int target) {
  if (target_hit) return;
  if (len >= target) { target_hit = 1; return; }
  int avail = full & ~pmask & ~forbid;
  if (len + pc(avail) < target) return;
  int cands = adj[last] & avail;
  int nf = forbid | adj[last];
  while (cands) {
    int w = cands & -cands; cands ^= w;
    dfsp2(adj, __builtin_ctz(w), pmask | w, nf, len + 1, full, target);
    if (target_hit) return;
  }
}


static void printg(int *adj, int n);
extern int report_tight_fwd;
#define report_tight report_tight_fwd
/* ---------- proven lower bounds on path(G) for C4-free G ---------- */
static int distmat[MAXV][MAXV];
static void alldist(int *adj, int n) {
  for (int s = 0; s < n; s++) {
    for (int v = 0; v < n; v++) distmat[s][v] = 99;
    int seen = 1 << s, fr = 1 << s, d = 0; distmat[s][s] = 0;
    while (1) {
      int nf = 0;
      for (int v = 0; v < n; v++) if (fr >> v & 1) nf |= adj[v];
      nf &= ~seen; if (!nf) break;
      seen |= nf; fr = nf; d++;
      for (int v = 0; v < n; v++) if (nf >> v & 1) distmat[s][v] = d;
    }
  }
}
/* P3: exists centre c, z at distance rad, y in N(z) at distance rad-1 from c,
   and x in N(z), x != y, x not adjacent y  ==>  path >= rad + 2 */
static int lb_P3(int *adj, int n, int r) {
  alldist(adj, n);
  for (int c = 0; c < n; c++) {
    int ecc = 0;
    for (int v = 0; v < n; v++) if (distmat[c][v] > ecc) ecc = distmat[c][v];
    if (ecc != r) continue;
    for (int z = 0; z < n; z++) {
      if (distmat[c][z] != r) continue;
      for (int y = 0; y < n; y++) {
        if (!(adj[z] >> y & 1)) continue;
        if (distmat[c][y] != r - 1) continue;
        for (int x = 0; x < n; x++) {
          if (!(adj[z] >> x & 1)) continue;
          if (x == y) continue;
          if (adj[x] >> y & 1) continue;
          return 1;
        }
      }
    }
  }
  return 0;
}
static long long cov_tot, cov_ok;
static long long g9_d3_fail = 0;
static long long n_diam2_tri=0, n_c6=0;
static long long n_gk_app[8]={0}, n_gk_bad[8]={0};
static long long n_l3=0, n_l3_mu2=0, n_resid_crit=0, n_resid_hard=0;   /* counts (u,z) at distance 3, both a>=2, path<6 */
static long long resid_prof[6][8];   /* [min(rad,5)][min(floorl,7)] */
static void coverage(int *adj, int n, int r, int fl) {
  int delta = 99, tri = 0;
  for (int v = 0; v < n; v++) { int d = pc(adj[v]); if (d < delta) delta = d; }
  for (int u = 0; u < n; u++) for (int v = u + 1; v < n; v++)
    if ((adj[u] >> v & 1) && (adj[u] & adj[v])) tri = 1;
  int need = r + fl;
  int lb = r + 1;                                  /* P1 */
  if (!tri) { if (delta >= 2 && delta + 2 > lb) lb = delta + 2; }  /* P2 girth>=5 */
  else      { if (delta >= 3 && delta + 1 > lb) lb = delta + 1; }  /* P2 C4-free  */
  if (lb_P3(adj, n, r) && r + 2 > lb) lb = r + 2;                  /* P3 */
  { int s = delta / 2 - 1; if (s > 0 && r + 1 + s > lb) lb = r + 1 + s; } /* P4 = Thm F */
  if (r >= 2 && r + 2 > lb) lb = r + 2;                            /* P5 = Theorem D */
  { int pth = pathnum(adj, n);
    if (r >= 2 && pth < r + 2) { printf("THEOREM-D FAILS rad=%d path=%d  ", r, pth); printg(adj,n); printf("\n"); exit(2); }
    if (!tri && delta >= 2 && pth < delta + 2) { printf("THEOREM-E1 FAILS delta=%d path=%d  ", delta, pth); printg(adj,n); printf("\n"); exit(2); }
    if (delta >= 3 && pth < delta + 1) { printf("THEOREM-E2 FAILS delta=%d path=%d  ", delta, pth); printg(adj,n); printf("\n"); exit(2); }
    if (delta >= 4 && pth < r + delta / 2) { printf("THEOREM-F FAILS rad=%d delta=%d path=%d  ", r, delta, pth); printg(adj,n); printf("\n"); exit(2); }
    if (r <= 1) { long S9 = 0; for (int v = 0; v < n; v++) S9 += alpha_rec(adj, adj[v]);
      if (S9 >= 2*(long)n) { printf("THEOREM-C FAILS rad=%d S=%ld n=%d  ", r, S9, n); printg(adj,n); printf("\n"); exit(2); } }

    /* ---------- owner-w133 additions, 2026-08-18 ----------------------- */
    /* a(v) = alpha(G[N(v)]); distmat[][] is already filled by lb_P3 above. */
    int av[MAXV]; int mu = 99, amax = 0;
    for (int v = 0; v < n; v++) { av[v] = alpha_rec(adj, adj[v]);
      if (av[v] < mu) mu = av[v]; if (av[v] > amax) amax = av[v]; }

    /* Lemma G1 (Qwen r>=3 round, already in draft): geodesic of length d>=2
       with a-values (>=3,>=2) at its ends  ==>  path >= d+3.               */
    for (int u = 0; u < n; u++) for (int z = 0; z < n; z++) {
      int d = distmat[u][z];
      if (d >= 2 && d < 90 && av[u] >= 3 && av[z] >= 2 && pth < d + 3) {
        printf("LEMMA-G1 FAILS d=%d a(u)=%d a(z)=%d path=%d  ", d, av[u], av[z], pth);
        printg(adj, n); printf("\n"); exit(2); }
    }
    /* Lemma G10 (new): geodesic of length d>=2 with a(u_d)>=2 ==> path >= d+2. */
    for (int u = 0; u < n; u++) for (int z = 0; z < n; z++) {
      int d = distmat[u][z];
      if (d >= 2 && d < 90 && av[z] >= 2 && pth < d + 2) {
        printf("LEMMA-G10 FAILS d=%d a(z)=%d path=%d  ", d, av[z], pth);
        printg(adj, n); printf("\n"); exit(2); }
    }
    /* Lemma G9 (new): geodesic of length d>=4 with BOTH ends a>=2 ==> path >= d+3. */
    for (int u = 0; u < n; u++) for (int z = 0; z < n; z++) {
      int d = distmat[u][z];
      if (d >= 4 && d < 90 && av[u] >= 2 && av[z] >= 2 && pth < d + 3) {
        printf("LEMMA-G9 FAILS d=%d a(u)=%d a(z)=%d path=%d  ", d, av[u], av[z], pth);
        printg(adj, n); printf("\n"); exit(2); }
    }
    /* Theorem G+ (new): no a=1 vertex and some a>=3 vertex ==> path >= rad+3. */
    int gplus = (r >= 2 && mu >= 2 && amax >= 3);
    if (gplus && pth < r + 3) {
      printf("THEOREM-Gplus FAILS rad=%d mu=%d amax=%d path=%d  ", r, mu, amax, pth);
      printg(adj, n); printf("\n"); exit(2); }
    /* d=3 probe: is Lemma G9 also true at d=3?  (recorded, not asserted)   */
    for (int u = 0; u < n; u++) for (int z = 0; z < n; z++)
      if (distmat[u][z] == 3 && av[u] >= 2 && av[z] >= 2 && pth < 6) g9_d3_fail++;
    /* ---- Lemma G15 (round 3): rigidity forced by an induced C6 ----------
       If G is C4-free, contains an induced 6-cycle Z, and path(G) <= 5, then
       every vertex outside Z has 0 or 2 neighbours on Z, and a pair of
       neighbours on Z is at cycle-distance 1 or 3 (never 2).
       Reason: exactly one neighbour v_i would extend the P5 = Z - v_{i+1}.   */
    if (pth <= 5) {
      int z[6];
      for (z[0] = 0; z[0] < n; z[0]++)
      for (z[1] = 0; z[1] < n; z[1]++) if (z[1]!=z[0] && (adj[z[0]]>>z[1]&1))
      for (z[2] = 0; z[2] < n; z[2]++) if (z[2]!=z[0]&&z[2]!=z[1] && (adj[z[1]]>>z[2]&1) && !(adj[z[0]]>>z[2]&1))
      for (z[3] = 0; z[3] < n; z[3]++) if (z[3]!=z[0]&&z[3]!=z[1]&&z[3]!=z[2] && (adj[z[2]]>>z[3]&1) && !(adj[z[0]]>>z[3]&1) && !(adj[z[1]]>>z[3]&1))
      for (z[4] = 0; z[4] < n; z[4]++) if (z[4]!=z[0]&&z[4]!=z[1]&&z[4]!=z[2]&&z[4]!=z[3] && (adj[z[3]]>>z[4]&1) && !(adj[z[0]]>>z[4]&1) && !(adj[z[1]]>>z[4]&1) && !(adj[z[2]]>>z[4]&1))
      for (z[5] = 0; z[5] < n; z[5]++) if (z[5]!=z[0]&&z[5]!=z[1]&&z[5]!=z[2]&&z[5]!=z[3]&&z[5]!=z[4]
            && (adj[z[4]]>>z[5]&1) && (adj[z[5]]>>z[0]&1) && !(adj[z[1]]>>z[5]&1) && !(adj[z[2]]>>z[5]&1) && !(adj[z[3]]>>z[5]&1)) {
        n_c6++;
        int Z = 0; for (int i = 0; i < 6; i++) Z |= 1 << z[i];
        for (int w = 0; w < n; w++) { if (Z>>w&1) continue;
          int cnt = 0, pos[6];
          for (int i = 0; i < 6; i++) if (adj[w]>>z[i]&1) pos[cnt++] = i;
          if (cnt == 1) { printf("LEMMA-G15 FAILS (exactly one nbr on C6) path=%d  ", pth); printg(adj,n); printf("\n"); exit(2); }
          for (int i = 0; i < cnt; i++) for (int j = i+1; j < cnt; j++) {
            int dd = pos[j]-pos[i]; if (dd > 3) dd = 6-dd;
            if (dd == 2) { printf("LEMMA-G15 FAILS (cycle-distance 2 pair) path=%d  ", pth); printg(adj,n); printf("\n"); exit(2); } }
        }
      }
    }
    /* ---- pocket-2 probe: does Theorem G+ generalise?  (G+k) conjecture:
           C4-free, mu >= k-1 and max a >= k  ==>  path >= rad + k.
           k=3 is Theorem G+ (PROVED).  T_m does NOT refute k>=4 because
           mu(T_m)=1.  Counted, NOT asserted -- a hit is a refutation.      */
    if (r >= 2) {
      for (int k = 4; k <= 6; k++)
        if (mu >= k - 1 && amax >= k) {
          n_gk_app[k]++;
          if (pth < r + k) { n_gk_bad[k]++;
            if (n_gk_bad[k] <= 3) {
              printf("Gplus-k REFUTED k=%d rad=%d mu=%d amax=%d path=%d  ", k, r, mu, amax, pth);
              printg(adj, n); printf("\n"); } } }
    }
    /* ---- Theorem G12 (round 2): diameter-2 C4-free graphs --------------
       Claims checked on EVERY triangle {a,b,c} of every diam-2 C4-free graph:
         (i)   A,B,C := N(a)\{b,c}, N(b)\{a,c}, N(c)\{a,b} are pairwise disjoint
               and pairwise non-adjacent;
         (ii)  every vertex of R := V\(T u A u B u C) has EXACTLY one neighbour
               in each of A, B, C;
         (iii) a(a) = 1 + comp(A)  and  a(x) = 1 + comp(R_x) for x in A
               (comp = number of components of the induced matching);
         (iv)  if path(G) <= 5 then R is a clique (hence |R| <= 3).
       And Theorem G12 itself: diam = 2 and l > 3  ==>  path >= 6.          */
    { int diam = 0;
      for (int u = 0; u < n; u++) for (int v = 0; v < n; v++)
        if (distmat[u][v] < 90 && distmat[u][v] > diam) diam = distmat[u][v];
      if (diam == 2) {
        long Sx = 0; for (int v = 0; v < n; v++) Sx += av[v];
        if (Sx > 3L * n && pth < 6) {
          printf("THEOREM-G12 FAILS n=%d S=%ld path=%d  ", n, Sx, pth);
          printg(adj, n); printf("\n"); exit(2); }
        int full = (1 << n) - 1;
        for (int a = 0; a < n; a++) for (int b = a+1; b < n; b++) for (int c = b+1; c < n; c++) {
          if (!((adj[a]>>b&1) && (adj[b]>>c&1) && (adj[a]>>c&1))) continue;
          n_diam2_tri++;
          int T = (1<<a)|(1<<b)|(1<<c);
          int NA = adj[a] & ~T, NB = adj[b] & ~T, NC = adj[c] & ~T;
          if ((NA&NB)||(NA&NC)||(NB&NC)) { printf("G12-i FAILS (overlap)  "); printg(adj,n); printf("\n"); exit(2); }
          for (int x = 0; x < n; x++) if (NA>>x&1) if (adj[x] & (NB|NC)) {
            printf("G12-i FAILS (A-B/A-C edge)  "); printg(adj,n); printf("\n"); exit(2); }
          for (int x = 0; x < n; x++) if (NB>>x&1) if (adj[x] & NC) {
            printf("G12-i FAILS (B-C edge)  "); printg(adj,n); printf("\n"); exit(2); }
          int R = full & ~T & ~NA & ~NB & ~NC;
          for (int u = 0; u < n; u++) if (R>>u&1) {
            if (pc(adj[u]&NA)!=1 || pc(adj[u]&NB)!=1 || pc(adj[u]&NC)!=1) {
              printf("G12-ii FAILS  "); printg(adj,n); printf("\n"); exit(2); } }
          /* comp(S) = |S| - e(S) for a set inducing a matching */
          #define COMPS(S) ({ int _s=(S), _e=0; for (int _i=0;_i<n;_i++) if (_s>>_i&1) _e += pc(adj[_i]&_s); pc(_s) - _e/2; })
          if (av[a] != 1 + COMPS(NA)) { printf("G12-iii FAILS a(a)  "); printg(adj,n); printf("\n"); exit(2); }
          for (int x = 0; x < n; x++) if (NA>>x&1) {
            int Rx = adj[x] & R;
            if (av[x] != 1 + COMPS(Rx)) { printf("G12-iii FAILS a(alpha)  "); printg(adj,n); printf("\n"); exit(2); } }
          if (pth <= 5) {
            for (int u = 0; u < n; u++) for (int v = u+1; v < n; v++)
              if ((R>>u&1)&&(R>>v&1)&&!(adj[u]>>v&1)) {
                printf("G12-iv FAILS (R not a clique) path=%d  ", pth); printg(adj,n); printf("\n"); exit(2); }
            if (pc(R) > 3) { printf("G12-iv FAILS (|R|>3) path=%d  ", pth); printg(adj,n); printf("\n"); exit(2); } }
        }
      } }
    /* --- census of the residual case of the peeling induction -----------
       Theorem X (target): C4-free + l>=3  ==>  path >= rad+3.
       Induction on n:  base  = no a=1 vertex        -> Theorem G+;
                        step  = delete v with a(v)=1 -> needs rad(G-v)=rad(G).
       Residual = l>=3, some a=1 vertex, and EVERY a=1 deletion drops the radius. */
    { long Sx = 0; for (int v = 0; v < n; v++) Sx += av[v];
      if (Sx >= 3L * n && r >= 2) {
        n_l3++;
        if (mu >= 2) n_l3_mu2++;
        else {
          int crit = 1;
          for (int v = 0; v < n && crit; v++) {
            if (av[v] != 1) continue;
            int sub[MAXV], k = 0, map[MAXV];
            for (int u = 0; u < n; u++) if (u != v) map[u] = k++;
            for (int u = 0; u < n; u++) { if (u == v) continue; int mm = 0;
              for (int w = 0; w < n; w++) if (w != v && (adj[u] >> w & 1)) mm |= 1 << map[w];
              sub[map[u]] = mm; }
            if (radiusG(sub, n - 1) == r) crit = 0;   /* radius-preserving deletion exists */
          }
          if (crit) { n_resid_crit++;
            int good = 0;
            for (int u = 0; u < n; u++) for (int z = 0; z < n; z++)
              if (distmat[u][z] >= r && distmat[u][z] < 90 && av[u] >= 3 && av[z] >= 2) good = 1;
            if (!good) { n_resid_hard++;
              printf("RESIDUAL-HARD n=%d rad=%d path=%d S=%ld  ", n, r, pth, Sx);
              printg(adj, n); printf("\n"); } } } } }
    if (gplus && r + 3 > lb) lb = r + 3;          /* fold G+ into coverage */
    { /* fold G1 into coverage: best d over good pairs */
      int bd = 0;
      for (int u = 0; u < n; u++) for (int z = 0; z < n; z++) {
        int d = distmat[u][z];
        if (d >= 2 && d < 90 && av[u] >= 3 && av[z] >= 2 && d > bd) bd = d; }
      if (bd && bd + 3 > lb) lb = bd + 3; }
  }
  cov_tot++;
  if (lb >= need) cov_ok++;
  else { resid_prof[r < 5 ? r : 5][fl < 7 ? fl : 7]++;
         if (report_tight) { printf("RESID n=%d rad=%d floorl=%d delta=%d tri=%d  ", n, r, fl, delta, tri); printg(adj, n); printf("\n"); } }
}

/* ------------------------------------------------------------------ */
/* test                                                                */
/* ------------------------------------------------------------------ */

static long long tested = 0, violations = 0, tight = 0;
static long long tight_by_n[MAXV + 1];
int report_tight_fwd = 0;
#undef report_tight
#define report_tight report_tight_fwd
static long long cnt_fl[8];          /* how many C4-free graphs with floor(l)=k */
static int minslack_fl[8];           /* min slack among those */
static long long tight_fl[8];

static void printg(int *adj, int n) {
  printf("n=%d E=[", n);
  int first = 1;
  for (int u = 0; u < n; u++)
    for (int v = u + 1; v < n; v++)
      if (adj[u] >> v & 1) { printf("%s(%d,%d)", first ? "" : ",", u, v); first = 0; }
  printf("]");
}

static void test(int *adj, int n) {
  tested++;
  NG = n;
  int r = radiusG(adj, n);
  int c4 = hasC4(adj, n);
  int rhs;
  int fl = 0;
  if (c4) {
    rhs = r + 1;
  } else {
    long S = 0;
    for (int v = 0; v < n; v++) S += alpha_rec(adj, adj[v]);
    fl = (int)(S / n);
    rhs = r + fl;
  }
  int p = pathnum(adj, n);
  if (!c4) {
    int k = fl < 7 ? fl : 7;
    cnt_fl[k]++;
    if (p - rhs < minslack_fl[k]) minslack_fl[k] = p - rhs;
    if (p == rhs) tight_fl[k]++;
    coverage(adj, n, r, fl);
    if (report_tight && p == rhs && fl >= 2) {
      printf("TIGHT2 path=%d rad=%d floorl=%d  ", p, r, fl); printg(adj, n); printf("\n");
    }
  }
  if (p < rhs) {
    violations++;
    printf("VIOLATION path=%d rad=%d c4=%d floorl=%d rhs=%d  ", p, r, c4, fl, rhs);
    printg(adj, n); printf("\n");
  } else if (p == rhs) {
    tight++; tight_by_n[n]++;
    if (report_tight && !c4) {
      printf("TIGHT path=%d rad=%d floorl=%d  ", p, r, fl);
      printg(adj, n); printf("\n");
    }
  }
}

/* ------------------------------------------------------------------ */
/* canonical form                                                      */
/* ------------------------------------------------------------------ */

static int col_[MAXV], tmpcol[MAXV];
typedef struct { unsigned char k[MAXV + 2]; int v; } KEY;
static int keycmp(const void *a, const void *b) {
  const KEY *x = a, *y = b;
  return memcmp(x->k, y->k, MAXV + 2);
}
static void wl(int *adj, int n) {
  for (int v = 0; v < n; v++) col_[v] = pc(adj[v]);
  for (int round = 0; round < n; round++) {
    KEY ks[MAXV];
    for (int v = 0; v < n; v++) {
      memset(ks[v].k, 0, MAXV + 2);
      ks[v].k[0] = (unsigned char)col_[v];
      unsigned char nb[MAXV]; int c = 0;
      for (int u = 0; u < n; u++) if (adj[v] >> u & 1) nb[c++] = (unsigned char)col_[u];
      for (int i = 1; i < c; i++) { unsigned char t = nb[i]; int j = i - 1;
        while (j >= 0 && nb[j] > t) { nb[j + 1] = nb[j]; j--; } nb[j + 1] = t; }
      ks[v].k[1] = (unsigned char)c;
      for (int i = 0; i < c; i++) ks[v].k[2 + i] = nb[i];
      ks[v].v = v;
    }
    KEY srt[MAXV];
    memcpy(srt, ks, sizeof(KEY) * n);
    qsort(srt, n, sizeof(KEY), keycmp);
    int rank = 0;
    for (int i = 0; i < n; i++) {
      if (i && keycmp(&srt[i], &srt[i - 1])) rank++;
      tmpcol[srt[i].v] = rank;
    }
    int changed = 0;
    for (int v = 0; v < n; v++) if (tmpcol[v] != col_[v]) changed = 1;
    for (int v = 0; v < n; v++) col_[v] = tmpcol[v];
    if (!changed) break;
  }
}

static int cn_, cadj_[MAXV], slotcol[MAXV], perm_[MAXV], usedm_;
static int curcert[MAXV], bestcert[MAXV];

static void canon_rec(int pos, int cs) {
  if (pos == cn_) {
    /* lexicographic compare curcert vs bestcert */
    for (int i = 0; i < cn_; i++) {
      if (curcert[i] < bestcert[i]) { memcpy(bestcert, curcert, sizeof(int) * cn_); return; }
      if (curcert[i] > bestcert[i]) return;
    }
    return;
  }
  for (int v = 0; v < cn_; v++) {
    if (usedm_ >> v & 1) continue;
    if (col_[v] != slotcol[pos]) continue;
    int row = 0;
    for (int j = 0; j < pos; j++) if (cadj_[v] >> perm_[j] & 1) row |= 1 << j;
    int ncs = cs;
    if (cs == 0) {
      if (row > bestcert[pos]) continue;
      if (row < bestcert[pos]) ncs = 1;
    }
    perm_[pos] = v; usedm_ |= 1 << v; curcert[pos] = row;
    canon_rec(pos + 1, ncs);
    usedm_ &= ~(1 << v);
  }
}

static u128 canon(int *adj, int n) {
  cn_ = n;
  memcpy(cadj_, adj, sizeof(int) * n);
  wl(adj, n);
  /* slot colours: sorted list of vertex colours */
  int cs2[MAXV];
  for (int v = 0; v < n; v++) cs2[v] = col_[v];
  for (int i = 1; i < n; i++) { int t = cs2[i], j = i - 1;
    while (j >= 0 && cs2[j] > t) { cs2[j + 1] = cs2[j]; j--; } cs2[j + 1] = t; }
  for (int i = 0; i < n; i++) slotcol[i] = cs2[i];
  for (int i = 0; i < n; i++) bestcert[i] = (1 << i) - 1;
  usedm_ = 0;
  canon_rec(0, 0);
  u128 c = 0;
  for (int i = 0; i < n; i++) c = (c << i) | (u128)(unsigned)bestcert[i];
  return c;
}

/* ------------------------------------------------------------------ */
/* hash set of certificates                                            */
/* ------------------------------------------------------------------ */

typedef struct { u128 *k; unsigned char *used; size_t cap, cnt; } HSET;
static void hs_init(HSET *h, size_t cap) {
  h->cap = cap; h->cnt = 0;
  h->k = malloc(sizeof(u128) * cap);
  h->used = calloc(cap, 1);
}
static void hs_free(HSET *h) { free(h->k); free(h->used); }
static int hs_insert(HSET *h, u128 key) { /* returns 1 if new */
  uint64_t lo = (uint64_t)key, hi = (uint64_t)(key >> 64);
  uint64_t x = lo * 0x9E3779B97F4A7C15ULL ^ (hi + 0x165667B19E3779F9ULL);
  x ^= x >> 29; x *= 0xBF58476D1CE4E5B9ULL; x ^= x >> 32;
  size_t i = (size_t)(x & (h->cap - 1));
  while (h->used[i]) {
    if (h->k[i] == key) return 0;
    i = (i + 1) & (h->cap - 1);
  }
  h->used[i] = 1; h->k[i] = key; h->cnt++;
  return 1;
}

/* ------------------------------------------------------------------ */

static int subs[1 << 17];
static int stack_set[1 << 17], stack_cand[1 << 17];
typedef struct { int *a; size_t cnt, cap; int n; } LIST;
static void l_init(LIST *L, int n) { L->n = n; L->cnt = 0; L->cap = 1024; L->a = malloc(sizeof(int) * MAXV * L->cap); }
static void l_push(LIST *L, int *adj) {
  if (L->cnt == L->cap) { L->cap *= 2; L->a = realloc(L->a, sizeof(int) * MAXV * L->cap); }
  memcpy(L->a + L->cnt * MAXV, adj, sizeof(int) * MAXV);
  L->cnt++;
}

int main(int argc, char **argv) {
  int MAXN = argc > 1 ? atoi(argv[1]) : 9;
  int c4free = argc > 2 ? atoi(argv[2]) : 0;
  report_tight = argc > 3 ? atoi(argv[3]) : 0;

  for (int k = 0; k < 8; k++) minslack_fl[k] = 1000;
  LIST cur, nxt;
  l_init(&cur, 2);
  int g0[MAXV]; memset(g0, 0, sizeof(g0));
  g0[0] = 2; g0[1] = 1;
  l_push(&cur, g0);
  test(g0, 2);
  printf("level n=2: classes=1 tested_total=%lld\n", tested);

  for (int n = 2; n < MAXN; n++) {
    l_init(&nxt, n + 1);
    HSET hs; hs_init(&hs, 1 << 22);
    int keep = (n + 1 < MAXN);
    for (size_t gi = 0; gi < cur.cnt; gi++) {
      int *base = cur.a + gi * MAXV;
      int nsubs = 0;
      if (!c4free) {
        for (int sub = 1; sub < (1 << n); sub++) subs[nsubs++] = sub;
      } else {
        /* valid neighbourhoods T: no two members share a neighbour in base */
        int conflict[MAXV];
        for (int u = 0; u < n; u++) {
          conflict[u] = 0;
          for (int v = 0; v < n; v++)
            if (v != u && (base[u] & base[v])) conflict[u] |= 1 << v;
        }
        /* enumerate all nonempty independent sets of `conflict` */
        int sp = 0;
        stack_set[sp] = 0; stack_cand[sp] = (1 << n) - 1; sp++;
        while (sp) {
          sp--;
          int S = stack_set[sp], C = stack_cand[sp];
          if (S) subs[nsubs++] = S;
          while (C) {
            int b = C & -C; C ^= b;
            int u = __builtin_ctz(b);
            stack_set[sp] = S | b;
            stack_cand[sp] = C & ~conflict[u];
            sp++;
          }
        }
      }
      for (int si = 0; si < nsubs; si++) {
        int sub = subs[si];
        int g[MAXV];
        memcpy(g, base, sizeof(int) * MAXV);
        g[n] = sub;
        for (int v = 0; v < n; v++) if (sub >> v & 1) g[v] |= 1 << n;
        if (c4free && hasC4(g, n + 1)) { printf("BUG: c4 leaked\n"); exit(1); }
        test(g, n + 1);
        if (keep) {
          u128 c = canon(g, n + 1);
          if (hs_insert(&hs, c)) l_push(&nxt, g);
        }
      }
    }
    printf("level n=%d: classes=%zu  tested_total=%lld  violations=%lld\n",
           n + 1, keep ? nxt.cnt : (size_t)0, tested, violations);
    fflush(stdout);
    hs_free(&hs);
    free(cur.a);
    cur = nxt;
  }
  printf("COVERAGE: C4-free tested=%lld covered_by_proved_lemmas=%lld (%.4f%%) residual=%lld\n", cov_tot, cov_ok, 100.0*cov_ok/(cov_tot?cov_tot:1), cov_tot-cov_ok);
  for (int a=0;a<6;a++) for (int b=0;b<8;b++) if (resid_prof[a][b]) printf("   residual rad=%d floor(l)=%d : %lld\n", a, b, resid_prof[a][b]);
  printf("L3-CENSUS: l>=3 graphs=%lld  of which mu>=2 (Thm G+ base case)=%lld  radius-critical residual=%lld  of which no-good-pair=%lld\n", n_l3, n_l3_mu2, n_resid_crit, n_resid_hard);
  for (int k=4;k<=6;k++) if (n_gk_app[k]) printf("Gplus-k PROBE k=%d: applicable=%lld  violations=%lld\n", k, n_gk_app[k], n_gk_bad[k]);
  printf("G15-CHECKS: induced-C6 instances (in path<=5 graphs) verified = %lld\n", n_c6);
  printf("G12-CHECKS: (diam-2 C4-free graph, triangle) pairs structurally verified = %lld\n", n_diam2_tri);
  printf("G9-d3-probe: (u,z) pairs at distance 3 with both a>=2 and path<6 : %lld\n", g9_d3_fail);
  printf("DONE tested=%lld violations=%lld tight=%lld\n", tested, violations, tight);
  for (int k = 0; k < 8; k++) if (cnt_fl[k]) printf("  C4-free floor(l)=%d: count=%lld minslack=%d tight=%lld\n", k, cnt_fl[k], minslack_fl[k], tight_fl[k]);
  for (int n = 2; n <= MAXN; n++) if (tight_by_n[n]) printf("  tight at n=%d: %lld\n", n, tight_by_n[n]);
  return 0;
}
