#!/usr/bin/env python3
"""Aggregate r5_scan / r5_bigsample output into markdown tables (data/summary.md).
Usage: python3 summarize.py data/scan_2_1e9.jsonl [more scan files] --big data/bigsample.jsonl data/bigsample_B.jsonl
"""
import argparse, json, math, collections
from sympy import factorint

def fmt_fac(m):
    return '·'.join(f'{p}^{e}' if e > 1 else f'{p}' for p, e in sorted(factorint(m).items()))

def v(n, k):
    return sum(1 for p in factorint(n + k) if p > k)

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('scans', nargs='+')
    ap.add_argument('--big', nargs='*', default=[])
    ap.add_argument('--out', default='data/summary.md')
    a = ap.parse_args()
    rows = []
    for fn in a.scans:
        rows += [json.loads(x) for x in open(fn)]
    rows.sort(key=lambda r: r['A'])
    L = []
    P = L.append
    lo = rows[0]['A']; hi = max(r['A'] + r['S'] for r in rows)
    P(f'# R5 summary (generated by summarize.py)\n\nExhaustive scan: n in [{lo}, {hi}), {len(rows)} segments.\n')
    # --- per decade ---
    dec = collections.defaultdict(list)
    for r in rows:
        d = int(math.floor(math.log10(max(r['A'], 2))))
        dec[d].append(r)
    for l in (0, 1, 2):
        P(f'\n## k3_{l}(n) = min{{k >= {l} : v(n,k) >= 3}} by decade (exact; "none" = no such k at all, i.e. v_{l}(n) <= 2)\n')
        P('| decade | #n | mean k3 | max k3 | at n | max k3/log n | at n | #none | largest none |')
        P('|---|---|---|---|---|---|---|---|---|')
        for d in sorted(dec):
            R = dec[d]
            hist = collections.Counter()
            for r in R:
                for k, c in r[f'l{l}']['hist'].items():
                    hist[int(k)] += c
            N = sum(hist.values()); mean = sum(k * c for k, c in hist.items()) / max(N, 1)
            best = max(R, key=lambda r: (r[f'l{l}']['max_k3'] or -1))
            bestr = max(R, key=lambda r: r[f'l{l}']['max_ratio_logn'])
            nn = sum(r[f'l{l}']['n_none'] for r in R)
            nones = [x for r in R for x in r[f'l{l}']['none']]
            P(f"| 10^{d} | {N + nn} | {mean:.3f} | {best[f'l{l}']['max_k3']} | {best[f'l{l}']['argmax']} | "
              f"{bestr[f'l{l}']['max_ratio_logn']:.2f} | {bestr[f'l{l}']['argmax_ratio']} | {nn} | {max(nones) if nones else '-'} |")
    # --- record progression (from per-segment top-20 lists) ---
    for l in (0, 1):
        P(f'\n## Record progression of k3_{l} (from per-segment top-20 lists; n <= 10^6 region may omit some records)\n')
        cur = -1; recs = []
        for r in rows:
            top = sorted(r[f'l{l}']['top'], key=lambda x: x[0])
            for n, k in top:
                if k > cur:
                    cur = k; recs.append((n, k))
        P('| n | k3 | k3/log n | k3/(log n/log log n) |'); P('|---|---|---|---|')
        for n, k in recs:
            if n >= 1000:
                ln = math.log(n)
                P(f'| {n} | {k} | {k/ln:.2f} | {k/(ln/math.log(ln)):.2f} |')
    # --- block statistics ---
    for C in (2, 5, 10):
        P(f'\n## Block statistics, K = floor({C} log n), l = 0, by decade\n')
        P('t_i = #{0<=j<=K : n+j has exactly i prime factors > K} (t3 = >=3), averaged over n; '
          'sigma0 = pi(K) - (2 t0 + t1) (R2 certificate), sigma = pi(K) - sum_{j in J} cap_j (R1 certificate); '
          'P-frac = #{p<=K : ceil(n/p) prime > K}/pi(K).\n')
        P('| decade | mean t0 | mean t1 | mean t2 | mean t3+ | frac sigma0<=0 | frac sigma<=0 | min sigma (n, K, pi(K)) | max (2t0+t1)/pi(K) | max t1 (n) | max P-frac (n) |')
        P('|---|---|---|---|---|---|---|---|---|---|---|')
        for d in sorted(dec):
            R = [r for r in dec[d] if r.get(f'C{C}') and r[f'C{C}']['count']]
            if not R:
                continue
            cnt = sum(r[f'C{C}']['count'] for r in R)
            st = [sum(r[f'C{C}']['sum_t'][i] for r in R) / cnt for i in range(4)]
            f0 = sum(r[f'C{C}']['n_sigma0_le0'] for r in R) / cnt
            f1 = sum(r[f'C{C}']['n_sigma_le0'] for r in R) / cnt
            ms = min((r[f'C{C}']['min_sigma'] for r in R), key=lambda x: x[0])
            mq = max((r[f'C{C}']['max_2t0t1_over_piK'] for r in R), key=lambda x: x[0])
            mt = max((r[f'C{C}']['max_t1'] for r in R), key=lambda x: x[0])
            mp = max((r[f'C{C}']['max_P_frac'] for r in R), key=lambda x: x[0])
            P(f'| 10^{d} | {st[0]:.2f} | {st[1]:.2f} | {st[2]:.2f} | {st[3]:.3f} | {f0:.4f} | {f1:.2e} | '
              f'{ms[0]} ({ms[1]}, {ms[2]}, {ms[3]}) | {mq[0]:.2f} ({mq[1]}) | {mt[0]} ({mt[1]}) | {mp[0]:.2f} ({mp[1]}) |')
    # --- large n samples ---
    if a.big:
        big = []
        for fn in a.big:
            big += [json.loads(x) for x in open(fn)]
        by = collections.defaultdict(list)
        for r in big:
            by[r['e']].append(r)
        P('\n## Sampled large n (uniform in [10^e, 2*10^e))\n')
        P('k3 exact for e <= 18 (full factorisation), otherwise a certified upper bound.\n')
        P('| e | #n | k3_0: mean / max | k3_1: mean / max | C | K | pi(K) | mean t0 | mean t1 | mean t2+ | mean t1/pi(K) | #sigma0<=0 | min sigma0 | #sigma<=0 | min sigma | mean Pcount |')
        P('|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|')
        for e in sorted(by):
            R = by[e]
            k0 = [r['k3_l0'] for r in R]; k1 = [r['k3_l1'] for r in R]
            for b in range(3):
                B = [r['blocks'][b] for r in R]
                C = B[0]['C']; Ks = [x['K'] for x in B]; pis = [x['piK'] for x in B]
                m = lambda key: sum(x[key] for x in B) / len(B)
                P(f"| {e} | {len(R)} | {sum(k0)/len(k0):.2f} / {max(k0)} | {sum(k1)/len(k1):.2f} / {max(k1)} | {C} | "
                  f"{min(Ks)}-{max(Ks)} | {min(pis)}-{max(pis)} | {m('t0'):.2f} | {m('t1'):.1f} | {m('t2p'):.1f} | "
                  f"{sum(x['t1']/x['piK'] for x in B)/len(B):.3f} | {sum(1 for x in B if x['sigma0']<=0)} | "
                  f"{min(x['sigma0'] for x in B)} | {sum(1 for x in B if x['sigma']<=0)} | {min(x['sigma'] for x in B)} | {m('Pc'):.2f} |")
    # --- worst-case structure ---
    P('\n## Structure of the largest k3_0 and k3_1 found (factorisations of n+k, k <= k3)\n')
    for l in (0, 1):
        allt = sorted({(k, n) for r in rows for n, k in r[f'l{l}']['top']}, reverse=True)[:3]
        for k3, n in allt:
            P(f'\n### l = {l}: n = {n} (= {fmt_fac(n)}), k3 = {k3}, log n = {math.log(n):.2f}\n')
            P('| k | v(n,k) | n+k factorised | primes > K=floor(10 log n) |')
            P('|---|---|---|---|')
            K = math.floor(10 * math.log(n))
            for k in range(l, k3 + 1):
                m = n + k
                P(f'| {k} | {v(n,k)} | {fmt_fac(m)} | {sum(1 for p in factorint(m) if p > K)} |')
    # --- anatomy of the worst R1-certificate failure at C = 10 in the top decade ---
    dtop = max(dec)
    worst = min((r['C10']['min_sigma'] for r in dec[dtop] if r['C10']['min_sigma']), key=lambda x: x[0])
    s0, n, K, piK = worst
    P(f'\n## Anatomy of the most negative R1 certificate, C = 10, decade 10^{dtop}: n = {n} (= {fmt_fac(n)}), K = {K}, pi(K) = {piK}, sigma = {s0}\n')
    P('J-positions only (d_j >= 1). cap_j = max(0, 2 - tau_j); the certificate fails because sum cap_j >= pi(K).\n')
    P('| j | d_j (entry primes in (j,K]) | tau_j (#primes > K) | cap_j | v(n,j) | n+j factorised |')
    P('|---|---|---|---|---|---|')
    tot = 0
    for j in range(K + 1):
        f = factorint(n + j)
        d = [p for p in f if j < p <= K]
        if not d:
            continue
        tau = sum(1 for p in f if p > K)
        cap = max(0, 2 - tau); tot += cap
        P(f'| {j} | {len(d)} {sorted(d)} | {tau} | {cap} | {len(d) + tau} | {fmt_fac(n + j)} |')
    P(f'\nsum over J of cap_j = {tot}; demand pi(K) = {piK}; sigma = {piK - tot}; k3_0(n) = '
      f'{next((k for k in range(0, 10**6) if v(n, k) >= 3), None)}\n')
    open(a.out, 'w').write('\n'.join(L) + '\n')
    print('\n'.join(L[:60]))

if __name__ == '__main__':
    main()
